project:
  base-dir: /home/seed

spring:
  application:
    name: Seed
  profiles:
    active:
  datasource:
    url: jdbc:h2:../test
    username: ENC(HGL/iymE+QVof9FATX1I7g==)
    password:
  # FIXME: 제거한다.
  h2:
    console:
      enabled: true
  security:
    custom:
      login-processing-url: /login
      login-page-url: /login.html
      username-parameter: id
      password-parameter: pw
      logout-url: /logout
      permit-all-urls: >
        /,
        /favicon.ico,
        /icon.svg,
        /login*.html,
        /logo*.svg,
        /css/**,
        /favicon/**,
        /js/**,
        /img/**,
        /fonts/**,
        /lang/**,
        /api/anon/**,
        /packetViewer/version.html,
        /packetViewer/packetviewer2.sfx.exe,
        /packetViewer/iptable.txt,
        /packetViewer/pcs2.ini
      deny-all-urls: >
        /login/**
      session:
        maximum-per-user: -1
        timeout: 1800
        exception-if-maximum-exceeded: false
      hide-user-not-found-exceptions: false

server:
  tomcat:
    accesslog:
      enabled: true
      directory: ${logging.file.path}/tomcat

logging:
  file:
    path: ${project.base-dir}/log
    name: ${logging.file.path}/${spring.application.name}.log
  logback:
    rollingpolicy:
      file-name-pattern: ${logging.file.path}/${spring.application.name}.%d{yyyy-MM-dd}_%i.log
      max-history: 30
      max-file-size: 10MB
  level:
    root: info
    com.innowireless: info

jasypt:
  encryptor:
    password: innoserversw2
    algorithm: PBEWithMD5AndDES
    iv-generator-classname: org.jasypt.iv.NoIvGenerator
    property:
      prefix: ENC(
      suffix: )

mybatis:
  base-packages: com.innowireless.web.mapper
  mapper-locations: mapper/*Mapper.xml
  configuration:
    default-statement-timeout: 300
    jdbc-type-for-null: null
    return-instance-for-empty-row: true
  configuration-properties:
    schema-name: public.
  type-aliases-package: org.apache.commons.collections4.map

springdoc:
  group-configs:
    - group: ADMIN API
      display-name: 관리자 API
      packages-to-scan: com.innowireless.web.api.admin
    - group: USER API
      display-name: 사용자 API
      packages-to-scan: com.innowireless.web.api.user
    - group: ANONYMOUS API
      display-name: 익명 사용자 API
      packages-to-scan: com.innowireless.web.api.anon

# FIXME: 제거한다.
test:
  task: 0/10 * * * * *
