project:
  base-dir: /home/seed
  test: # TODO: 사용하지 않을 경우 해당 옵션을 제거한다.
    alive-task1:
      time: '-'
    alive-task2:
      enable: false
      time: 0/30 * * * * *

spring:
  application:
    name: Seed
  profiles:
    active: dev
  datasource:
    # TODO: 데이터베이스 접속 정보를 작성한다.
    url: jdbc:postgresql://{ip}:{port}/{db_name}
    username: {username}
    password: {password}
  security:
    custom:
      index-page-url: /index.html
      login-url-prefix: /api/anon/login
      login-url-pattern: ${spring.security.custom.login-url-prefix}/**
      login-page-url: /login.html
      username-parameter: id
      password-parameter: pw
      logout-url: /api/anon/logout
      permit-all-urls: >
        /,
        /favicon.ico,
        /icon.svg,
        /login*.html,
        /logo*.svg,
        /css/**,
        /favicon/**,
        /js/**,
        /img/**,
        /fonts/**,
        /lang/**,
        /api/anon/**,
        /packetViewer/version.html,
        /packetViewer/packetviewer2.sfx.exe,
        /packetViewer/iptable.txt,
        /packetViewer/pcs2.ini
      session:
        maximum-per-user: 1
        timeout: 1800
        exception-if-maximum-exceeded: false
      hide-user-not-found-exceptions: false

server:
  tomcat:
    accesslog:
      enabled: true
      directory: ${logging.file.path}/tomcat
  compression:
    enabled: true
    mime-types: text/html, text/xml, text/plain, text/css, text/javascript, application/javascript, application/json

logging:
  file:
    path: ${project.base-dir}/log
    name: ${logging.file.path}/${spring.application.name}.log
  logback:
    rollingpolicy:
      file-name-pattern: ${logging.file.path}/${spring.application.name}.%d{yyyy-MM-dd}_%i.log
      max-history: 30
      max-file-size: 10MB
  level:
    root: info
    com.innowireless: info

jasypt:
  encryptor:
    password: innoserversw2
    algorithm: PBEWithMD5AndDES
    iv-generator-classname: org.jasypt.iv.NoIvGenerator
    property:
      prefix: ENC(
      suffix: )

mybatis:
  base-packages: com.innowireless.web.mapper
  mapper-locations: mapper/*Mapper.xml
  configuration:
    default-statement-timeout: 300
    jdbc-type-for-null: null
    return-instance-for-empty-row: true
  configuration-properties:
    schema-name: public.
  type-aliases-package: org.apache.commons.collections4.map

springdoc:
  group-configs:
    - group: ADMIN API
      display-name: 관리자 API
      packages-to-scan: com.innowireless.web.api.admin
    - group: USER API
      display-name: 사용자 API
      packages-to-scan: com.innowireless.web.api.user
    - group: ANONYMOUS API
      display-name: 익명 사용자 API
      packages-to-scan: com.innowireless.web.api.anon
