project:
  base-dir: /home/seed
  test: # TODO: 사용하지 않을 경우 해당 옵션을 제거한다.
    alive-task1:
      time: 0/30 * * * * *
    alive-task2:
      enable: true
      time: 0/30 * * * * *

spring:
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
  sql:
    init:
      mode: always
      schema-locations: classpath:h2/schema.sql
      data-locations: classpath:h2/data.sql
  h2:
    console:
      enabled: true
  security:
    custom:
      permit-all-urls: >
        /,
        /favicon.ico,
        /icon.svg,
        /login*.html,
        /logo*.svg,
        /css/**,
        /favicon/**,
        /js/**,
        /img/**,
        /fonts/**,
        /lang/**,
        /api/anon/**,
        /packetViewer/version.html,
        /packetViewer/packetviewer2.sfx.exe,
        /packetViewer/iptable.txt,
        /packetViewer/pcs2.ini,
        /h2-console/**

logging:
  level:
    com.innowireless.web.task: debug
