version: '2'
networks:
  customer_support_net:
    ipam:
      config:
        - subnet: 172.31.0.0/24
services:
  db:
    image: 10.253.12.86:12000/customer_support_db:latest #image명
    container_name: customer_support_db #image Container명
    ports:
      - '10.253.12.86:11800:5432' #외부 11300 : 내부 5432
    volumes:
      - /home/docker_admin/docker_volumes/customer_support/db:/var/lib/postgresql/data #외부볼륨 local path : Container path
    networks:
      customer_support_net:
        ipv4_address: 172.31.0.10
    restart: always
  web:
    image: 10.253.12.86:12000/customer_support_web:latest #image명
    container_name: customer_support_web #image Container명
    mem_limit: 2048m
    environment:
      JAVA_OPTS: '-XshowSettings:vm
                  -Xmx1500m
                  -Xms1024m'
    ports:
      - '11801:8080' #외부 11301 : 내부 8080
    volumes:
      - /home/docker_admin/docker_volumes/customer_support/web:/home/docker_admin/docker_volumes/customer_support/web #외부볼륨 local path : Container path
      - /etc/timezone:/etc/timezone:ro # 시간 동기화
      - /etc/localtime:/etc/localtime:ro
    networks:
      customer_support_net:
        ipv4_address: 172.31.0.11
    restart: always  
    depends_on:
      - db    