// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: xdb_5gcp_rui.proto

package com.innowireless.xdb5gcp.rui;

/**
 * <pre>
 * every gRPC response messages (except stream) contain BaseResult to return general error
 * before using a response message, user has to check if ResultCode is valid (RESULT_OK)
 * </pre>
 *
 * Protobuf type {@code xdb_5gcp.rui.BaseResult}
 */
public  final class BaseResult extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:xdb_5gcp.rui.BaseResult)
    BaseResultOrBuilder {
private static final long serialVersionUID = 0L;
  // Use BaseResult.newBuilder() to construct.
  private BaseResult(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private BaseResult() {
    resultCode_ = 0;
    errorMessage_ = "";
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private BaseResult(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
          case 8: {
            int rawValue = input.readEnum();

            resultCode_ = rawValue;
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            errorMessage_ = s;
            break;
          }
          case 26: {
            com.innowireless.xdb5gcp.rui.BaseResult.SyntaxErrorPos.Builder subBuilder = null;
            if (syntaxErrorPos_ != null) {
              subBuilder = syntaxErrorPos_.toBuilder();
            }
            syntaxErrorPos_ = input.readMessage(com.innowireless.xdb5gcp.rui.BaseResult.SyntaxErrorPos.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(syntaxErrorPos_);
              syntaxErrorPos_ = subBuilder.buildPartial();
            }

            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.innowireless.xdb5gcp.rui.RuiProto.internal_static_xdb_5gcp_rui_BaseResult_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.innowireless.xdb5gcp.rui.RuiProto.internal_static_xdb_5gcp_rui_BaseResult_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.innowireless.xdb5gcp.rui.BaseResult.class, com.innowireless.xdb5gcp.rui.BaseResult.Builder.class);
  }

  /**
   * Protobuf enum {@code xdb_5gcp.rui.BaseResult.ResultCode}
   */
  public enum ResultCode
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>RESULT_OK = 0;</code>
     */
    RESULT_OK(0),
    /**
     * <code>RESULT_ERROR = 1;</code>
     */
    RESULT_ERROR(1),
    /**
     * <code>RESULT_KEY_NOT_FOUND = 2;</code>
     */
    RESULT_KEY_NOT_FOUND(2),
    /**
     * <code>RESULT_INPUT_SYNTAX_ERROR = 3;</code>
     */
    RESULT_INPUT_SYNTAX_ERROR(3),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>RESULT_OK = 0;</code>
     */
    public static final int RESULT_OK_VALUE = 0;
    /**
     * <code>RESULT_ERROR = 1;</code>
     */
    public static final int RESULT_ERROR_VALUE = 1;
    /**
     * <code>RESULT_KEY_NOT_FOUND = 2;</code>
     */
    public static final int RESULT_KEY_NOT_FOUND_VALUE = 2;
    /**
     * <code>RESULT_INPUT_SYNTAX_ERROR = 3;</code>
     */
    public static final int RESULT_INPUT_SYNTAX_ERROR_VALUE = 3;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static ResultCode valueOf(int value) {
      return forNumber(value);
    }

    public static ResultCode forNumber(int value) {
      switch (value) {
        case 0: return RESULT_OK;
        case 1: return RESULT_ERROR;
        case 2: return RESULT_KEY_NOT_FOUND;
        case 3: return RESULT_INPUT_SYNTAX_ERROR;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<ResultCode>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        ResultCode> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<ResultCode>() {
            public ResultCode findValueByNumber(int number) {
              return ResultCode.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.innowireless.xdb5gcp.rui.BaseResult.getDescriptor().getEnumTypes().get(0);
    }

    private static final ResultCode[] VALUES = values();

    public static ResultCode valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private ResultCode(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:xdb_5gcp.rui.BaseResult.ResultCode)
  }

  public interface SyntaxErrorPosOrBuilder extends
      // @@protoc_insertion_point(interface_extends:xdb_5gcp.rui.BaseResult.SyntaxErrorPos)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>bool error_pos_exist = 1;</code>
     */
    boolean getErrorPosExist();

    /**
     * <code>int32 start_line = 2;</code>
     */
    int getStartLine();

    /**
     * <code>int32 end_line = 3;</code>
     */
    int getEndLine();

    /**
     * <code>int32 start_pos = 4;</code>
     */
    int getStartPos();

    /**
     * <code>int32 end_pos = 5;</code>
     */
    int getEndPos();
  }
  /**
   * <pre>
   * when result code is RESULT_INPUT_SYNTAX_ERROR and error_pos_exist is true,
   * valid position data will be in SyntaxErrorPos message
   * </pre>
   *
   * Protobuf type {@code xdb_5gcp.rui.BaseResult.SyntaxErrorPos}
   */
  public  static final class SyntaxErrorPos extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:xdb_5gcp.rui.BaseResult.SyntaxErrorPos)
      SyntaxErrorPosOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use SyntaxErrorPos.newBuilder() to construct.
    private SyntaxErrorPos(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private SyntaxErrorPos() {
      errorPosExist_ = false;
      startLine_ = 0;
      endLine_ = 0;
      startPos_ = 0;
      endPos_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private SyntaxErrorPos(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              errorPosExist_ = input.readBool();
              break;
            }
            case 16: {

              startLine_ = input.readInt32();
              break;
            }
            case 24: {

              endLine_ = input.readInt32();
              break;
            }
            case 32: {

              startPos_ = input.readInt32();
              break;
            }
            case 40: {

              endPos_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.innowireless.xdb5gcp.rui.RuiProto.internal_static_xdb_5gcp_rui_BaseResult_SyntaxErrorPos_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.innowireless.xdb5gcp.rui.RuiProto.internal_static_xdb_5gcp_rui_BaseResult_SyntaxErrorPos_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.innowireless.xdb5gcp.rui.BaseResult.SyntaxErrorPos.class, com.innowireless.xdb5gcp.rui.BaseResult.SyntaxErrorPos.Builder.class);
    }

    public static final int ERROR_POS_EXIST_FIELD_NUMBER = 1;
    private boolean errorPosExist_;
    /**
     * <code>bool error_pos_exist = 1;</code>
     */
    public boolean getErrorPosExist() {
      return errorPosExist_;
    }

    public static final int START_LINE_FIELD_NUMBER = 2;
    private int startLine_;
    /**
     * <code>int32 start_line = 2;</code>
     */
    public int getStartLine() {
      return startLine_;
    }

    public static final int END_LINE_FIELD_NUMBER = 3;
    private int endLine_;
    /**
     * <code>int32 end_line = 3;</code>
     */
    public int getEndLine() {
      return endLine_;
    }

    public static final int START_POS_FIELD_NUMBER = 4;
    private int startPos_;
    /**
     * <code>int32 start_pos = 4;</code>
     */
    public int getStartPos() {
      return startPos_;
    }

    public static final int END_POS_FIELD_NUMBER = 5;
    private int endPos_;
    /**
     * <code>int32 end_pos = 5;</code>
     */
    public int getEndPos() {
      return endPos_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (errorPosExist_ != false) {
        output.writeBool(1, errorPosExist_);
      }
      if (startLine_ != 0) {
        output.writeInt32(2, startLine_);
      }
      if (endLine_ != 0) {
        output.writeInt32(3, endLine_);
      }
      if (startPos_ != 0) {
        output.writeInt32(4, startPos_);
      }
      if (endPos_ != 0) {
        output.writeInt32(5, endPos_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (errorPosExist_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(1, errorPosExist_);
      }
      if (startLine_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, startLine_);
      }
      if (endLine_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, endLine_);
      }
      if (startPos_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, startPos_);
      }
      if (endPos_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(5, endPos_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.innowireless.xdb5gcp.rui.BaseResult.SyntaxErrorPos)) {
        return super.equals(obj);
      }
      com.innowireless.xdb5gcp.rui.BaseResult.SyntaxErrorPos other = (com.innowireless.xdb5gcp.rui.BaseResult.SyntaxErrorPos) obj;

      boolean result = true;
      result = result && (getErrorPosExist()
          == other.getErrorPosExist());
      result = result && (getStartLine()
          == other.getStartLine());
      result = result && (getEndLine()
          == other.getEndLine());
      result = result && (getStartPos()
          == other.getStartPos());
      result = result && (getEndPos()
          == other.getEndPos());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ERROR_POS_EXIST_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getErrorPosExist());
      hash = (37 * hash) + START_LINE_FIELD_NUMBER;
      hash = (53 * hash) + getStartLine();
      hash = (37 * hash) + END_LINE_FIELD_NUMBER;
      hash = (53 * hash) + getEndLine();
      hash = (37 * hash) + START_POS_FIELD_NUMBER;
      hash = (53 * hash) + getStartPos();
      hash = (37 * hash) + END_POS_FIELD_NUMBER;
      hash = (53 * hash) + getEndPos();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.innowireless.xdb5gcp.rui.BaseResult.SyntaxErrorPos parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.innowireless.xdb5gcp.rui.BaseResult.SyntaxErrorPos parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.innowireless.xdb5gcp.rui.BaseResult.SyntaxErrorPos parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.innowireless.xdb5gcp.rui.BaseResult.SyntaxErrorPos parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.innowireless.xdb5gcp.rui.BaseResult.SyntaxErrorPos parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.innowireless.xdb5gcp.rui.BaseResult.SyntaxErrorPos parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.innowireless.xdb5gcp.rui.BaseResult.SyntaxErrorPos parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.innowireless.xdb5gcp.rui.BaseResult.SyntaxErrorPos parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.innowireless.xdb5gcp.rui.BaseResult.SyntaxErrorPos parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.innowireless.xdb5gcp.rui.BaseResult.SyntaxErrorPos parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.innowireless.xdb5gcp.rui.BaseResult.SyntaxErrorPos parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.innowireless.xdb5gcp.rui.BaseResult.SyntaxErrorPos parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.innowireless.xdb5gcp.rui.BaseResult.SyntaxErrorPos prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * when result code is RESULT_INPUT_SYNTAX_ERROR and error_pos_exist is true,
     * valid position data will be in SyntaxErrorPos message
     * </pre>
     *
     * Protobuf type {@code xdb_5gcp.rui.BaseResult.SyntaxErrorPos}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:xdb_5gcp.rui.BaseResult.SyntaxErrorPos)
        com.innowireless.xdb5gcp.rui.BaseResult.SyntaxErrorPosOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.innowireless.xdb5gcp.rui.RuiProto.internal_static_xdb_5gcp_rui_BaseResult_SyntaxErrorPos_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.innowireless.xdb5gcp.rui.RuiProto.internal_static_xdb_5gcp_rui_BaseResult_SyntaxErrorPos_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.innowireless.xdb5gcp.rui.BaseResult.SyntaxErrorPos.class, com.innowireless.xdb5gcp.rui.BaseResult.SyntaxErrorPos.Builder.class);
      }

      // Construct using com.innowireless.xdb5gcp.rui.BaseResult.SyntaxErrorPos.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        errorPosExist_ = false;

        startLine_ = 0;

        endLine_ = 0;

        startPos_ = 0;

        endPos_ = 0;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.innowireless.xdb5gcp.rui.RuiProto.internal_static_xdb_5gcp_rui_BaseResult_SyntaxErrorPos_descriptor;
      }

      public com.innowireless.xdb5gcp.rui.BaseResult.SyntaxErrorPos getDefaultInstanceForType() {
        return com.innowireless.xdb5gcp.rui.BaseResult.SyntaxErrorPos.getDefaultInstance();
      }

      public com.innowireless.xdb5gcp.rui.BaseResult.SyntaxErrorPos build() {
        com.innowireless.xdb5gcp.rui.BaseResult.SyntaxErrorPos result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.innowireless.xdb5gcp.rui.BaseResult.SyntaxErrorPos buildPartial() {
        com.innowireless.xdb5gcp.rui.BaseResult.SyntaxErrorPos result = new com.innowireless.xdb5gcp.rui.BaseResult.SyntaxErrorPos(this);
        result.errorPosExist_ = errorPosExist_;
        result.startLine_ = startLine_;
        result.endLine_ = endLine_;
        result.startPos_ = startPos_;
        result.endPos_ = endPos_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.innowireless.xdb5gcp.rui.BaseResult.SyntaxErrorPos) {
          return mergeFrom((com.innowireless.xdb5gcp.rui.BaseResult.SyntaxErrorPos)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.innowireless.xdb5gcp.rui.BaseResult.SyntaxErrorPos other) {
        if (other == com.innowireless.xdb5gcp.rui.BaseResult.SyntaxErrorPos.getDefaultInstance()) return this;
        if (other.getErrorPosExist() != false) {
          setErrorPosExist(other.getErrorPosExist());
        }
        if (other.getStartLine() != 0) {
          setStartLine(other.getStartLine());
        }
        if (other.getEndLine() != 0) {
          setEndLine(other.getEndLine());
        }
        if (other.getStartPos() != 0) {
          setStartPos(other.getStartPos());
        }
        if (other.getEndPos() != 0) {
          setEndPos(other.getEndPos());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.innowireless.xdb5gcp.rui.BaseResult.SyntaxErrorPos parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.innowireless.xdb5gcp.rui.BaseResult.SyntaxErrorPos) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private boolean errorPosExist_ ;
      /**
       * <code>bool error_pos_exist = 1;</code>
       */
      public boolean getErrorPosExist() {
        return errorPosExist_;
      }
      /**
       * <code>bool error_pos_exist = 1;</code>
       */
      public Builder setErrorPosExist(boolean value) {
        
        errorPosExist_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bool error_pos_exist = 1;</code>
       */
      public Builder clearErrorPosExist() {
        
        errorPosExist_ = false;
        onChanged();
        return this;
      }

      private int startLine_ ;
      /**
       * <code>int32 start_line = 2;</code>
       */
      public int getStartLine() {
        return startLine_;
      }
      /**
       * <code>int32 start_line = 2;</code>
       */
      public Builder setStartLine(int value) {
        
        startLine_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 start_line = 2;</code>
       */
      public Builder clearStartLine() {
        
        startLine_ = 0;
        onChanged();
        return this;
      }

      private int endLine_ ;
      /**
       * <code>int32 end_line = 3;</code>
       */
      public int getEndLine() {
        return endLine_;
      }
      /**
       * <code>int32 end_line = 3;</code>
       */
      public Builder setEndLine(int value) {
        
        endLine_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 end_line = 3;</code>
       */
      public Builder clearEndLine() {
        
        endLine_ = 0;
        onChanged();
        return this;
      }

      private int startPos_ ;
      /**
       * <code>int32 start_pos = 4;</code>
       */
      public int getStartPos() {
        return startPos_;
      }
      /**
       * <code>int32 start_pos = 4;</code>
       */
      public Builder setStartPos(int value) {
        
        startPos_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 start_pos = 4;</code>
       */
      public Builder clearStartPos() {
        
        startPos_ = 0;
        onChanged();
        return this;
      }

      private int endPos_ ;
      /**
       * <code>int32 end_pos = 5;</code>
       */
      public int getEndPos() {
        return endPos_;
      }
      /**
       * <code>int32 end_pos = 5;</code>
       */
      public Builder setEndPos(int value) {
        
        endPos_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 end_pos = 5;</code>
       */
      public Builder clearEndPos() {
        
        endPos_ = 0;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:xdb_5gcp.rui.BaseResult.SyntaxErrorPos)
    }

    // @@protoc_insertion_point(class_scope:xdb_5gcp.rui.BaseResult.SyntaxErrorPos)
    private static final com.innowireless.xdb5gcp.rui.BaseResult.SyntaxErrorPos DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.innowireless.xdb5gcp.rui.BaseResult.SyntaxErrorPos();
    }

    public static com.innowireless.xdb5gcp.rui.BaseResult.SyntaxErrorPos getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<SyntaxErrorPos>
        PARSER = new com.google.protobuf.AbstractParser<SyntaxErrorPos>() {
      public SyntaxErrorPos parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new SyntaxErrorPos(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<SyntaxErrorPos> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<SyntaxErrorPos> getParserForType() {
      return PARSER;
    }

    public com.innowireless.xdb5gcp.rui.BaseResult.SyntaxErrorPos getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public static final int RESULT_CODE_FIELD_NUMBER = 1;
  private int resultCode_;
  /**
   * <code>.xdb_5gcp.rui.BaseResult.ResultCode result_code = 1;</code>
   */
  public int getResultCodeValue() {
    return resultCode_;
  }
  /**
   * <code>.xdb_5gcp.rui.BaseResult.ResultCode result_code = 1;</code>
   */
  public com.innowireless.xdb5gcp.rui.BaseResult.ResultCode getResultCode() {
    com.innowireless.xdb5gcp.rui.BaseResult.ResultCode result = com.innowireless.xdb5gcp.rui.BaseResult.ResultCode.valueOf(resultCode_);
    return result == null ? com.innowireless.xdb5gcp.rui.BaseResult.ResultCode.UNRECOGNIZED : result;
  }

  public static final int ERROR_MESSAGE_FIELD_NUMBER = 2;
  private volatile java.lang.Object errorMessage_;
  /**
   * <code>string error_message = 2;</code>
   */
  public java.lang.String getErrorMessage() {
    java.lang.Object ref = errorMessage_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      errorMessage_ = s;
      return s;
    }
  }
  /**
   * <code>string error_message = 2;</code>
   */
  public com.google.protobuf.ByteString
      getErrorMessageBytes() {
    java.lang.Object ref = errorMessage_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      errorMessage_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int SYNTAX_ERROR_POS_FIELD_NUMBER = 3;
  private com.innowireless.xdb5gcp.rui.BaseResult.SyntaxErrorPos syntaxErrorPos_;
  /**
   * <code>.xdb_5gcp.rui.BaseResult.SyntaxErrorPos syntax_error_pos = 3;</code>
   */
  public boolean hasSyntaxErrorPos() {
    return syntaxErrorPos_ != null;
  }
  /**
   * <code>.xdb_5gcp.rui.BaseResult.SyntaxErrorPos syntax_error_pos = 3;</code>
   */
  public com.innowireless.xdb5gcp.rui.BaseResult.SyntaxErrorPos getSyntaxErrorPos() {
    return syntaxErrorPos_ == null ? com.innowireless.xdb5gcp.rui.BaseResult.SyntaxErrorPos.getDefaultInstance() : syntaxErrorPos_;
  }
  /**
   * <code>.xdb_5gcp.rui.BaseResult.SyntaxErrorPos syntax_error_pos = 3;</code>
   */
  public com.innowireless.xdb5gcp.rui.BaseResult.SyntaxErrorPosOrBuilder getSyntaxErrorPosOrBuilder() {
    return getSyntaxErrorPos();
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (resultCode_ != com.innowireless.xdb5gcp.rui.BaseResult.ResultCode.RESULT_OK.getNumber()) {
      output.writeEnum(1, resultCode_);
    }
    if (!getErrorMessageBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, errorMessage_);
    }
    if (syntaxErrorPos_ != null) {
      output.writeMessage(3, getSyntaxErrorPos());
    }
    unknownFields.writeTo(output);
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (resultCode_ != com.innowireless.xdb5gcp.rui.BaseResult.ResultCode.RESULT_OK.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(1, resultCode_);
    }
    if (!getErrorMessageBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, errorMessage_);
    }
    if (syntaxErrorPos_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, getSyntaxErrorPos());
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.innowireless.xdb5gcp.rui.BaseResult)) {
      return super.equals(obj);
    }
    com.innowireless.xdb5gcp.rui.BaseResult other = (com.innowireless.xdb5gcp.rui.BaseResult) obj;

    boolean result = true;
    result = result && resultCode_ == other.resultCode_;
    result = result && getErrorMessage()
        .equals(other.getErrorMessage());
    result = result && (hasSyntaxErrorPos() == other.hasSyntaxErrorPos());
    if (hasSyntaxErrorPos()) {
      result = result && getSyntaxErrorPos()
          .equals(other.getSyntaxErrorPos());
    }
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + RESULT_CODE_FIELD_NUMBER;
    hash = (53 * hash) + resultCode_;
    hash = (37 * hash) + ERROR_MESSAGE_FIELD_NUMBER;
    hash = (53 * hash) + getErrorMessage().hashCode();
    if (hasSyntaxErrorPos()) {
      hash = (37 * hash) + SYNTAX_ERROR_POS_FIELD_NUMBER;
      hash = (53 * hash) + getSyntaxErrorPos().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.innowireless.xdb5gcp.rui.BaseResult parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.innowireless.xdb5gcp.rui.BaseResult parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.innowireless.xdb5gcp.rui.BaseResult parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.innowireless.xdb5gcp.rui.BaseResult parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.innowireless.xdb5gcp.rui.BaseResult parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.innowireless.xdb5gcp.rui.BaseResult parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.innowireless.xdb5gcp.rui.BaseResult parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.innowireless.xdb5gcp.rui.BaseResult parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.innowireless.xdb5gcp.rui.BaseResult parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.innowireless.xdb5gcp.rui.BaseResult parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.innowireless.xdb5gcp.rui.BaseResult parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.innowireless.xdb5gcp.rui.BaseResult parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.innowireless.xdb5gcp.rui.BaseResult prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * every gRPC response messages (except stream) contain BaseResult to return general error
   * before using a response message, user has to check if ResultCode is valid (RESULT_OK)
   * </pre>
   *
   * Protobuf type {@code xdb_5gcp.rui.BaseResult}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:xdb_5gcp.rui.BaseResult)
      com.innowireless.xdb5gcp.rui.BaseResultOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.innowireless.xdb5gcp.rui.RuiProto.internal_static_xdb_5gcp_rui_BaseResult_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.innowireless.xdb5gcp.rui.RuiProto.internal_static_xdb_5gcp_rui_BaseResult_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.innowireless.xdb5gcp.rui.BaseResult.class, com.innowireless.xdb5gcp.rui.BaseResult.Builder.class);
    }

    // Construct using com.innowireless.xdb5gcp.rui.BaseResult.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      resultCode_ = 0;

      errorMessage_ = "";

      if (syntaxErrorPosBuilder_ == null) {
        syntaxErrorPos_ = null;
      } else {
        syntaxErrorPos_ = null;
        syntaxErrorPosBuilder_ = null;
      }
      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.innowireless.xdb5gcp.rui.RuiProto.internal_static_xdb_5gcp_rui_BaseResult_descriptor;
    }

    public com.innowireless.xdb5gcp.rui.BaseResult getDefaultInstanceForType() {
      return com.innowireless.xdb5gcp.rui.BaseResult.getDefaultInstance();
    }

    public com.innowireless.xdb5gcp.rui.BaseResult build() {
      com.innowireless.xdb5gcp.rui.BaseResult result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public com.innowireless.xdb5gcp.rui.BaseResult buildPartial() {
      com.innowireless.xdb5gcp.rui.BaseResult result = new com.innowireless.xdb5gcp.rui.BaseResult(this);
      result.resultCode_ = resultCode_;
      result.errorMessage_ = errorMessage_;
      if (syntaxErrorPosBuilder_ == null) {
        result.syntaxErrorPos_ = syntaxErrorPos_;
      } else {
        result.syntaxErrorPos_ = syntaxErrorPosBuilder_.build();
      }
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.innowireless.xdb5gcp.rui.BaseResult) {
        return mergeFrom((com.innowireless.xdb5gcp.rui.BaseResult)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.innowireless.xdb5gcp.rui.BaseResult other) {
      if (other == com.innowireless.xdb5gcp.rui.BaseResult.getDefaultInstance()) return this;
      if (other.resultCode_ != 0) {
        setResultCodeValue(other.getResultCodeValue());
      }
      if (!other.getErrorMessage().isEmpty()) {
        errorMessage_ = other.errorMessage_;
        onChanged();
      }
      if (other.hasSyntaxErrorPos()) {
        mergeSyntaxErrorPos(other.getSyntaxErrorPos());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.innowireless.xdb5gcp.rui.BaseResult parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.innowireless.xdb5gcp.rui.BaseResult) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private int resultCode_ = 0;
    /**
     * <code>.xdb_5gcp.rui.BaseResult.ResultCode result_code = 1;</code>
     */
    public int getResultCodeValue() {
      return resultCode_;
    }
    /**
     * <code>.xdb_5gcp.rui.BaseResult.ResultCode result_code = 1;</code>
     */
    public Builder setResultCodeValue(int value) {
      resultCode_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>.xdb_5gcp.rui.BaseResult.ResultCode result_code = 1;</code>
     */
    public com.innowireless.xdb5gcp.rui.BaseResult.ResultCode getResultCode() {
      com.innowireless.xdb5gcp.rui.BaseResult.ResultCode result = com.innowireless.xdb5gcp.rui.BaseResult.ResultCode.valueOf(resultCode_);
      return result == null ? com.innowireless.xdb5gcp.rui.BaseResult.ResultCode.UNRECOGNIZED : result;
    }
    /**
     * <code>.xdb_5gcp.rui.BaseResult.ResultCode result_code = 1;</code>
     */
    public Builder setResultCode(com.innowireless.xdb5gcp.rui.BaseResult.ResultCode value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      resultCode_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.xdb_5gcp.rui.BaseResult.ResultCode result_code = 1;</code>
     */
    public Builder clearResultCode() {
      
      resultCode_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object errorMessage_ = "";
    /**
     * <code>string error_message = 2;</code>
     */
    public java.lang.String getErrorMessage() {
      java.lang.Object ref = errorMessage_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        errorMessage_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string error_message = 2;</code>
     */
    public com.google.protobuf.ByteString
        getErrorMessageBytes() {
      java.lang.Object ref = errorMessage_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        errorMessage_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string error_message = 2;</code>
     */
    public Builder setErrorMessage(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      errorMessage_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string error_message = 2;</code>
     */
    public Builder clearErrorMessage() {
      
      errorMessage_ = getDefaultInstance().getErrorMessage();
      onChanged();
      return this;
    }
    /**
     * <code>string error_message = 2;</code>
     */
    public Builder setErrorMessageBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      errorMessage_ = value;
      onChanged();
      return this;
    }

    private com.innowireless.xdb5gcp.rui.BaseResult.SyntaxErrorPos syntaxErrorPos_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.innowireless.xdb5gcp.rui.BaseResult.SyntaxErrorPos, com.innowireless.xdb5gcp.rui.BaseResult.SyntaxErrorPos.Builder, com.innowireless.xdb5gcp.rui.BaseResult.SyntaxErrorPosOrBuilder> syntaxErrorPosBuilder_;
    /**
     * <code>.xdb_5gcp.rui.BaseResult.SyntaxErrorPos syntax_error_pos = 3;</code>
     */
    public boolean hasSyntaxErrorPos() {
      return syntaxErrorPosBuilder_ != null || syntaxErrorPos_ != null;
    }
    /**
     * <code>.xdb_5gcp.rui.BaseResult.SyntaxErrorPos syntax_error_pos = 3;</code>
     */
    public com.innowireless.xdb5gcp.rui.BaseResult.SyntaxErrorPos getSyntaxErrorPos() {
      if (syntaxErrorPosBuilder_ == null) {
        return syntaxErrorPos_ == null ? com.innowireless.xdb5gcp.rui.BaseResult.SyntaxErrorPos.getDefaultInstance() : syntaxErrorPos_;
      } else {
        return syntaxErrorPosBuilder_.getMessage();
      }
    }
    /**
     * <code>.xdb_5gcp.rui.BaseResult.SyntaxErrorPos syntax_error_pos = 3;</code>
     */
    public Builder setSyntaxErrorPos(com.innowireless.xdb5gcp.rui.BaseResult.SyntaxErrorPos value) {
      if (syntaxErrorPosBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        syntaxErrorPos_ = value;
        onChanged();
      } else {
        syntaxErrorPosBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.xdb_5gcp.rui.BaseResult.SyntaxErrorPos syntax_error_pos = 3;</code>
     */
    public Builder setSyntaxErrorPos(
        com.innowireless.xdb5gcp.rui.BaseResult.SyntaxErrorPos.Builder builderForValue) {
      if (syntaxErrorPosBuilder_ == null) {
        syntaxErrorPos_ = builderForValue.build();
        onChanged();
      } else {
        syntaxErrorPosBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.xdb_5gcp.rui.BaseResult.SyntaxErrorPos syntax_error_pos = 3;</code>
     */
    public Builder mergeSyntaxErrorPos(com.innowireless.xdb5gcp.rui.BaseResult.SyntaxErrorPos value) {
      if (syntaxErrorPosBuilder_ == null) {
        if (syntaxErrorPos_ != null) {
          syntaxErrorPos_ =
            com.innowireless.xdb5gcp.rui.BaseResult.SyntaxErrorPos.newBuilder(syntaxErrorPos_).mergeFrom(value).buildPartial();
        } else {
          syntaxErrorPos_ = value;
        }
        onChanged();
      } else {
        syntaxErrorPosBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.xdb_5gcp.rui.BaseResult.SyntaxErrorPos syntax_error_pos = 3;</code>
     */
    public Builder clearSyntaxErrorPos() {
      if (syntaxErrorPosBuilder_ == null) {
        syntaxErrorPos_ = null;
        onChanged();
      } else {
        syntaxErrorPos_ = null;
        syntaxErrorPosBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.xdb_5gcp.rui.BaseResult.SyntaxErrorPos syntax_error_pos = 3;</code>
     */
    public com.innowireless.xdb5gcp.rui.BaseResult.SyntaxErrorPos.Builder getSyntaxErrorPosBuilder() {
      
      onChanged();
      return getSyntaxErrorPosFieldBuilder().getBuilder();
    }
    /**
     * <code>.xdb_5gcp.rui.BaseResult.SyntaxErrorPos syntax_error_pos = 3;</code>
     */
    public com.innowireless.xdb5gcp.rui.BaseResult.SyntaxErrorPosOrBuilder getSyntaxErrorPosOrBuilder() {
      if (syntaxErrorPosBuilder_ != null) {
        return syntaxErrorPosBuilder_.getMessageOrBuilder();
      } else {
        return syntaxErrorPos_ == null ?
            com.innowireless.xdb5gcp.rui.BaseResult.SyntaxErrorPos.getDefaultInstance() : syntaxErrorPos_;
      }
    }
    /**
     * <code>.xdb_5gcp.rui.BaseResult.SyntaxErrorPos syntax_error_pos = 3;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.innowireless.xdb5gcp.rui.BaseResult.SyntaxErrorPos, com.innowireless.xdb5gcp.rui.BaseResult.SyntaxErrorPos.Builder, com.innowireless.xdb5gcp.rui.BaseResult.SyntaxErrorPosOrBuilder> 
        getSyntaxErrorPosFieldBuilder() {
      if (syntaxErrorPosBuilder_ == null) {
        syntaxErrorPosBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.innowireless.xdb5gcp.rui.BaseResult.SyntaxErrorPos, com.innowireless.xdb5gcp.rui.BaseResult.SyntaxErrorPos.Builder, com.innowireless.xdb5gcp.rui.BaseResult.SyntaxErrorPosOrBuilder>(
                getSyntaxErrorPos(),
                getParentForChildren(),
                isClean());
        syntaxErrorPos_ = null;
      }
      return syntaxErrorPosBuilder_;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:xdb_5gcp.rui.BaseResult)
  }

  // @@protoc_insertion_point(class_scope:xdb_5gcp.rui.BaseResult)
  private static final com.innowireless.xdb5gcp.rui.BaseResult DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.innowireless.xdb5gcp.rui.BaseResult();
  }

  public static com.innowireless.xdb5gcp.rui.BaseResult getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<BaseResult>
      PARSER = new com.google.protobuf.AbstractParser<BaseResult>() {
    public BaseResult parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new BaseResult(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<BaseResult> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<BaseResult> getParserForType() {
    return PARSER;
  }

  public com.innowireless.xdb5gcp.rui.BaseResult getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

