// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: xdb_5gcp_rui.proto

package com.innowireless.xdb5gcp.rui;

public interface DatasetOrBuilder extends
    // @@protoc_insertion_point(interface_extends:xdb_5gcp.rui.Dataset)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated string record = 1;</code>
   */
  java.util.List<java.lang.String>
      getRecordList();
  /**
   * <code>repeated string record = 1;</code>
   */
  int getRecordCount();
  /**
   * <code>repeated string record = 1;</code>
   */
  java.lang.String getRecord(int index);
  /**
   * <code>repeated string record = 1;</code>
   */
  com.google.protobuf.ByteString
      getRecordBytes(int index);
}
