// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: xdb_5gcp_rui.proto

package com.innowireless.xdb5gcp.rui;

public interface EmptyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:xdb_5gcp.rui.Empty)
    com.google.protobuf.MessageOrBuilder {
}
