// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: xdb_5gcp_rui.proto

package com.innowireless.xdb5gcp.rui;

public interface ExecutionResultOrBuilder extends
    // @@protoc_insertion_point(interface_extends:xdb_5gcp.rui.ExecutionResult)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.xdb_5gcp.rui.BaseResult base_result = 1;</code>
   */
  boolean hasBaseResult();
  /**
   * <code>.xdb_5gcp.rui.BaseResult base_result = 1;</code>
   */
  com.innowireless.xdb5gcp.rui.BaseResult getBaseResult();
  /**
   * <code>.xdb_5gcp.rui.BaseResult base_result = 1;</code>
   */
  com.innowireless.xdb5gcp.rui.BaseResultOrBuilder getBaseResultOrBuilder();

  /**
   * <code>.xdb_5gcp.rui.SqlType sql_type = 2;</code>
   */
  int getSqlTypeValue();
  /**
   * <code>.xdb_5gcp.rui.SqlType sql_type = 2;</code>
   */
  com.innowireless.xdb5gcp.rui.SqlType getSqlType();

  /**
   * <code>.xdb_5gcp.rui.ExecutionResult.ExecutionStatus execution_status = 3;</code>
   */
  int getExecutionStatusValue();
  /**
   * <code>.xdb_5gcp.rui.ExecutionResult.ExecutionStatus execution_status = 3;</code>
   */
  com.innowireless.xdb5gcp.rui.ExecutionResult.ExecutionStatus getExecutionStatus();

  /**
   * <code>.xdb_5gcp.rui.ExecutionResult.ExecutionErrorCode execution_error_code = 4;</code>
   */
  int getExecutionErrorCodeValue();
  /**
   * <code>.xdb_5gcp.rui.ExecutionResult.ExecutionErrorCode execution_error_code = 4;</code>
   */
  com.innowireless.xdb5gcp.rui.ExecutionResult.ExecutionErrorCode getExecutionErrorCode();

  /**
   * <code>string execution_message = 5;</code>
   */
  java.lang.String getExecutionMessage();
  /**
   * <code>string execution_message = 5;</code>
   */
  com.google.protobuf.ByteString
      getExecutionMessageBytes();

  /**
   * <pre>
   * milliseconds
   * </pre>
   *
   * <code>int64 execution_time = 6;</code>
   */
  long getExecutionTime();

  /**
   * <code>int64 result_row_count = 7;</code>
   */
  long getResultRowCount();
}
