// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: xdb_5gcp_rui.proto

package com.innowireless.xdb5gcp.rui;

/**
 * Protobuf type {@code xdb_5gcp.rui.ExecutionResult}
 */
public  final class ExecutionResult extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:xdb_5gcp.rui.ExecutionResult)
    ExecutionResultOrBuilder {
private static final long serialVersionUID = 0L;
  // Use ExecutionResult.newBuilder() to construct.
  private ExecutionResult(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ExecutionResult() {
    sqlType_ = 0;
    executionStatus_ = 0;
    executionErrorCode_ = 0;
    executionMessage_ = "";
    executionTime_ = 0L;
    resultRowCount_ = 0L;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private ExecutionResult(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            com.innowireless.xdb5gcp.rui.BaseResult.Builder subBuilder = null;
            if (baseResult_ != null) {
              subBuilder = baseResult_.toBuilder();
            }
            baseResult_ = input.readMessage(com.innowireless.xdb5gcp.rui.BaseResult.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(baseResult_);
              baseResult_ = subBuilder.buildPartial();
            }

            break;
          }
          case 16: {
            int rawValue = input.readEnum();

            sqlType_ = rawValue;
            break;
          }
          case 24: {
            int rawValue = input.readEnum();

            executionStatus_ = rawValue;
            break;
          }
          case 32: {
            int rawValue = input.readEnum();

            executionErrorCode_ = rawValue;
            break;
          }
          case 42: {
            java.lang.String s = input.readStringRequireUtf8();

            executionMessage_ = s;
            break;
          }
          case 48: {

            executionTime_ = input.readInt64();
            break;
          }
          case 56: {

            resultRowCount_ = input.readInt64();
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.innowireless.xdb5gcp.rui.RuiProto.internal_static_xdb_5gcp_rui_ExecutionResult_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.innowireless.xdb5gcp.rui.RuiProto.internal_static_xdb_5gcp_rui_ExecutionResult_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.innowireless.xdb5gcp.rui.ExecutionResult.class, com.innowireless.xdb5gcp.rui.ExecutionResult.Builder.class);
  }

  /**
   * Protobuf enum {@code xdb_5gcp.rui.ExecutionResult.ExecutionStatus}
   */
  public enum ExecutionStatus
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>STATUS_UNKNOWN = 0;</code>
     */
    STATUS_UNKNOWN(0),
    /**
     * <code>STATUS_READY = 1;</code>
     */
    STATUS_READY(1),
    /**
     * <code>STATUS_RUNNING = 2;</code>
     */
    STATUS_RUNNING(2),
    /**
     * <code>STATUS_DONE = 3;</code>
     */
    STATUS_DONE(3),
    /**
     * <code>STATUS_ERROR = 4;</code>
     */
    STATUS_ERROR(4),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>STATUS_UNKNOWN = 0;</code>
     */
    public static final int STATUS_UNKNOWN_VALUE = 0;
    /**
     * <code>STATUS_READY = 1;</code>
     */
    public static final int STATUS_READY_VALUE = 1;
    /**
     * <code>STATUS_RUNNING = 2;</code>
     */
    public static final int STATUS_RUNNING_VALUE = 2;
    /**
     * <code>STATUS_DONE = 3;</code>
     */
    public static final int STATUS_DONE_VALUE = 3;
    /**
     * <code>STATUS_ERROR = 4;</code>
     */
    public static final int STATUS_ERROR_VALUE = 4;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static ExecutionStatus valueOf(int value) {
      return forNumber(value);
    }

    public static ExecutionStatus forNumber(int value) {
      switch (value) {
        case 0: return STATUS_UNKNOWN;
        case 1: return STATUS_READY;
        case 2: return STATUS_RUNNING;
        case 3: return STATUS_DONE;
        case 4: return STATUS_ERROR;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<ExecutionStatus>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        ExecutionStatus> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<ExecutionStatus>() {
            public ExecutionStatus findValueByNumber(int number) {
              return ExecutionStatus.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.innowireless.xdb5gcp.rui.ExecutionResult.getDescriptor().getEnumTypes().get(0);
    }

    private static final ExecutionStatus[] VALUES = values();

    public static ExecutionStatus valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private ExecutionStatus(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:xdb_5gcp.rui.ExecutionResult.ExecutionStatus)
  }

  /**
   * Protobuf enum {@code xdb_5gcp.rui.ExecutionResult.ExecutionErrorCode}
   */
  public enum ExecutionErrorCode
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>NOT_ERROR = 0;</code>
     */
    NOT_ERROR(0),
    /**
     * <code>UNKNOWN_ERROR = 1;</code>
     */
    UNKNOWN_ERROR(1),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>NOT_ERROR = 0;</code>
     */
    public static final int NOT_ERROR_VALUE = 0;
    /**
     * <code>UNKNOWN_ERROR = 1;</code>
     */
    public static final int UNKNOWN_ERROR_VALUE = 1;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static ExecutionErrorCode valueOf(int value) {
      return forNumber(value);
    }

    public static ExecutionErrorCode forNumber(int value) {
      switch (value) {
        case 0: return NOT_ERROR;
        case 1: return UNKNOWN_ERROR;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<ExecutionErrorCode>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        ExecutionErrorCode> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<ExecutionErrorCode>() {
            public ExecutionErrorCode findValueByNumber(int number) {
              return ExecutionErrorCode.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.innowireless.xdb5gcp.rui.ExecutionResult.getDescriptor().getEnumTypes().get(1);
    }

    private static final ExecutionErrorCode[] VALUES = values();

    public static ExecutionErrorCode valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private ExecutionErrorCode(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:xdb_5gcp.rui.ExecutionResult.ExecutionErrorCode)
  }

  public static final int BASE_RESULT_FIELD_NUMBER = 1;
  private com.innowireless.xdb5gcp.rui.BaseResult baseResult_;
  /**
   * <code>.xdb_5gcp.rui.BaseResult base_result = 1;</code>
   */
  public boolean hasBaseResult() {
    return baseResult_ != null;
  }
  /**
   * <code>.xdb_5gcp.rui.BaseResult base_result = 1;</code>
   */
  public com.innowireless.xdb5gcp.rui.BaseResult getBaseResult() {
    return baseResult_ == null ? com.innowireless.xdb5gcp.rui.BaseResult.getDefaultInstance() : baseResult_;
  }
  /**
   * <code>.xdb_5gcp.rui.BaseResult base_result = 1;</code>
   */
  public com.innowireless.xdb5gcp.rui.BaseResultOrBuilder getBaseResultOrBuilder() {
    return getBaseResult();
  }

  public static final int SQL_TYPE_FIELD_NUMBER = 2;
  private int sqlType_;
  /**
   * <code>.xdb_5gcp.rui.SqlType sql_type = 2;</code>
   */
  public int getSqlTypeValue() {
    return sqlType_;
  }
  /**
   * <code>.xdb_5gcp.rui.SqlType sql_type = 2;</code>
   */
  public com.innowireless.xdb5gcp.rui.SqlType getSqlType() {
    com.innowireless.xdb5gcp.rui.SqlType result = com.innowireless.xdb5gcp.rui.SqlType.valueOf(sqlType_);
    return result == null ? com.innowireless.xdb5gcp.rui.SqlType.UNRECOGNIZED : result;
  }

  public static final int EXECUTION_STATUS_FIELD_NUMBER = 3;
  private int executionStatus_;
  /**
   * <code>.xdb_5gcp.rui.ExecutionResult.ExecutionStatus execution_status = 3;</code>
   */
  public int getExecutionStatusValue() {
    return executionStatus_;
  }
  /**
   * <code>.xdb_5gcp.rui.ExecutionResult.ExecutionStatus execution_status = 3;</code>
   */
  public com.innowireless.xdb5gcp.rui.ExecutionResult.ExecutionStatus getExecutionStatus() {
    com.innowireless.xdb5gcp.rui.ExecutionResult.ExecutionStatus result = com.innowireless.xdb5gcp.rui.ExecutionResult.ExecutionStatus.valueOf(executionStatus_);
    return result == null ? com.innowireless.xdb5gcp.rui.ExecutionResult.ExecutionStatus.UNRECOGNIZED : result;
  }

  public static final int EXECUTION_ERROR_CODE_FIELD_NUMBER = 4;
  private int executionErrorCode_;
  /**
   * <code>.xdb_5gcp.rui.ExecutionResult.ExecutionErrorCode execution_error_code = 4;</code>
   */
  public int getExecutionErrorCodeValue() {
    return executionErrorCode_;
  }
  /**
   * <code>.xdb_5gcp.rui.ExecutionResult.ExecutionErrorCode execution_error_code = 4;</code>
   */
  public com.innowireless.xdb5gcp.rui.ExecutionResult.ExecutionErrorCode getExecutionErrorCode() {
    com.innowireless.xdb5gcp.rui.ExecutionResult.ExecutionErrorCode result = com.innowireless.xdb5gcp.rui.ExecutionResult.ExecutionErrorCode.valueOf(executionErrorCode_);
    return result == null ? com.innowireless.xdb5gcp.rui.ExecutionResult.ExecutionErrorCode.UNRECOGNIZED : result;
  }

  public static final int EXECUTION_MESSAGE_FIELD_NUMBER = 5;
  private volatile java.lang.Object executionMessage_;
  /**
   * <code>string execution_message = 5;</code>
   */
  public java.lang.String getExecutionMessage() {
    java.lang.Object ref = executionMessage_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      executionMessage_ = s;
      return s;
    }
  }
  /**
   * <code>string execution_message = 5;</code>
   */
  public com.google.protobuf.ByteString
      getExecutionMessageBytes() {
    java.lang.Object ref = executionMessage_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      executionMessage_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int EXECUTION_TIME_FIELD_NUMBER = 6;
  private long executionTime_;
  /**
   * <pre>
   * milliseconds
   * </pre>
   *
   * <code>int64 execution_time = 6;</code>
   */
  public long getExecutionTime() {
    return executionTime_;
  }

  public static final int RESULT_ROW_COUNT_FIELD_NUMBER = 7;
  private long resultRowCount_;
  /**
   * <code>int64 result_row_count = 7;</code>
   */
  public long getResultRowCount() {
    return resultRowCount_;
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (baseResult_ != null) {
      output.writeMessage(1, getBaseResult());
    }
    if (sqlType_ != com.innowireless.xdb5gcp.rui.SqlType.SELECT_STMT.getNumber()) {
      output.writeEnum(2, sqlType_);
    }
    if (executionStatus_ != com.innowireless.xdb5gcp.rui.ExecutionResult.ExecutionStatus.STATUS_UNKNOWN.getNumber()) {
      output.writeEnum(3, executionStatus_);
    }
    if (executionErrorCode_ != com.innowireless.xdb5gcp.rui.ExecutionResult.ExecutionErrorCode.NOT_ERROR.getNumber()) {
      output.writeEnum(4, executionErrorCode_);
    }
    if (!getExecutionMessageBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 5, executionMessage_);
    }
    if (executionTime_ != 0L) {
      output.writeInt64(6, executionTime_);
    }
    if (resultRowCount_ != 0L) {
      output.writeInt64(7, resultRowCount_);
    }
    unknownFields.writeTo(output);
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (baseResult_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getBaseResult());
    }
    if (sqlType_ != com.innowireless.xdb5gcp.rui.SqlType.SELECT_STMT.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(2, sqlType_);
    }
    if (executionStatus_ != com.innowireless.xdb5gcp.rui.ExecutionResult.ExecutionStatus.STATUS_UNKNOWN.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(3, executionStatus_);
    }
    if (executionErrorCode_ != com.innowireless.xdb5gcp.rui.ExecutionResult.ExecutionErrorCode.NOT_ERROR.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(4, executionErrorCode_);
    }
    if (!getExecutionMessageBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, executionMessage_);
    }
    if (executionTime_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(6, executionTime_);
    }
    if (resultRowCount_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(7, resultRowCount_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.innowireless.xdb5gcp.rui.ExecutionResult)) {
      return super.equals(obj);
    }
    com.innowireless.xdb5gcp.rui.ExecutionResult other = (com.innowireless.xdb5gcp.rui.ExecutionResult) obj;

    boolean result = true;
    result = result && (hasBaseResult() == other.hasBaseResult());
    if (hasBaseResult()) {
      result = result && getBaseResult()
          .equals(other.getBaseResult());
    }
    result = result && sqlType_ == other.sqlType_;
    result = result && executionStatus_ == other.executionStatus_;
    result = result && executionErrorCode_ == other.executionErrorCode_;
    result = result && getExecutionMessage()
        .equals(other.getExecutionMessage());
    result = result && (getExecutionTime()
        == other.getExecutionTime());
    result = result && (getResultRowCount()
        == other.getResultRowCount());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasBaseResult()) {
      hash = (37 * hash) + BASE_RESULT_FIELD_NUMBER;
      hash = (53 * hash) + getBaseResult().hashCode();
    }
    hash = (37 * hash) + SQL_TYPE_FIELD_NUMBER;
    hash = (53 * hash) + sqlType_;
    hash = (37 * hash) + EXECUTION_STATUS_FIELD_NUMBER;
    hash = (53 * hash) + executionStatus_;
    hash = (37 * hash) + EXECUTION_ERROR_CODE_FIELD_NUMBER;
    hash = (53 * hash) + executionErrorCode_;
    hash = (37 * hash) + EXECUTION_MESSAGE_FIELD_NUMBER;
    hash = (53 * hash) + getExecutionMessage().hashCode();
    hash = (37 * hash) + EXECUTION_TIME_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getExecutionTime());
    hash = (37 * hash) + RESULT_ROW_COUNT_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getResultRowCount());
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.innowireless.xdb5gcp.rui.ExecutionResult parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.innowireless.xdb5gcp.rui.ExecutionResult parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.innowireless.xdb5gcp.rui.ExecutionResult parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.innowireless.xdb5gcp.rui.ExecutionResult parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.innowireless.xdb5gcp.rui.ExecutionResult parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.innowireless.xdb5gcp.rui.ExecutionResult parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.innowireless.xdb5gcp.rui.ExecutionResult parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.innowireless.xdb5gcp.rui.ExecutionResult parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.innowireless.xdb5gcp.rui.ExecutionResult parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.innowireless.xdb5gcp.rui.ExecutionResult parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.innowireless.xdb5gcp.rui.ExecutionResult parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.innowireless.xdb5gcp.rui.ExecutionResult parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.innowireless.xdb5gcp.rui.ExecutionResult prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code xdb_5gcp.rui.ExecutionResult}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:xdb_5gcp.rui.ExecutionResult)
      com.innowireless.xdb5gcp.rui.ExecutionResultOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.innowireless.xdb5gcp.rui.RuiProto.internal_static_xdb_5gcp_rui_ExecutionResult_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.innowireless.xdb5gcp.rui.RuiProto.internal_static_xdb_5gcp_rui_ExecutionResult_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.innowireless.xdb5gcp.rui.ExecutionResult.class, com.innowireless.xdb5gcp.rui.ExecutionResult.Builder.class);
    }

    // Construct using com.innowireless.xdb5gcp.rui.ExecutionResult.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      if (baseResultBuilder_ == null) {
        baseResult_ = null;
      } else {
        baseResult_ = null;
        baseResultBuilder_ = null;
      }
      sqlType_ = 0;

      executionStatus_ = 0;

      executionErrorCode_ = 0;

      executionMessage_ = "";

      executionTime_ = 0L;

      resultRowCount_ = 0L;

      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.innowireless.xdb5gcp.rui.RuiProto.internal_static_xdb_5gcp_rui_ExecutionResult_descriptor;
    }

    public com.innowireless.xdb5gcp.rui.ExecutionResult getDefaultInstanceForType() {
      return com.innowireless.xdb5gcp.rui.ExecutionResult.getDefaultInstance();
    }

    public com.innowireless.xdb5gcp.rui.ExecutionResult build() {
      com.innowireless.xdb5gcp.rui.ExecutionResult result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public com.innowireless.xdb5gcp.rui.ExecutionResult buildPartial() {
      com.innowireless.xdb5gcp.rui.ExecutionResult result = new com.innowireless.xdb5gcp.rui.ExecutionResult(this);
      if (baseResultBuilder_ == null) {
        result.baseResult_ = baseResult_;
      } else {
        result.baseResult_ = baseResultBuilder_.build();
      }
      result.sqlType_ = sqlType_;
      result.executionStatus_ = executionStatus_;
      result.executionErrorCode_ = executionErrorCode_;
      result.executionMessage_ = executionMessage_;
      result.executionTime_ = executionTime_;
      result.resultRowCount_ = resultRowCount_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.innowireless.xdb5gcp.rui.ExecutionResult) {
        return mergeFrom((com.innowireless.xdb5gcp.rui.ExecutionResult)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.innowireless.xdb5gcp.rui.ExecutionResult other) {
      if (other == com.innowireless.xdb5gcp.rui.ExecutionResult.getDefaultInstance()) return this;
      if (other.hasBaseResult()) {
        mergeBaseResult(other.getBaseResult());
      }
      if (other.sqlType_ != 0) {
        setSqlTypeValue(other.getSqlTypeValue());
      }
      if (other.executionStatus_ != 0) {
        setExecutionStatusValue(other.getExecutionStatusValue());
      }
      if (other.executionErrorCode_ != 0) {
        setExecutionErrorCodeValue(other.getExecutionErrorCodeValue());
      }
      if (!other.getExecutionMessage().isEmpty()) {
        executionMessage_ = other.executionMessage_;
        onChanged();
      }
      if (other.getExecutionTime() != 0L) {
        setExecutionTime(other.getExecutionTime());
      }
      if (other.getResultRowCount() != 0L) {
        setResultRowCount(other.getResultRowCount());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.innowireless.xdb5gcp.rui.ExecutionResult parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.innowireless.xdb5gcp.rui.ExecutionResult) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private com.innowireless.xdb5gcp.rui.BaseResult baseResult_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.innowireless.xdb5gcp.rui.BaseResult, com.innowireless.xdb5gcp.rui.BaseResult.Builder, com.innowireless.xdb5gcp.rui.BaseResultOrBuilder> baseResultBuilder_;
    /**
     * <code>.xdb_5gcp.rui.BaseResult base_result = 1;</code>
     */
    public boolean hasBaseResult() {
      return baseResultBuilder_ != null || baseResult_ != null;
    }
    /**
     * <code>.xdb_5gcp.rui.BaseResult base_result = 1;</code>
     */
    public com.innowireless.xdb5gcp.rui.BaseResult getBaseResult() {
      if (baseResultBuilder_ == null) {
        return baseResult_ == null ? com.innowireless.xdb5gcp.rui.BaseResult.getDefaultInstance() : baseResult_;
      } else {
        return baseResultBuilder_.getMessage();
      }
    }
    /**
     * <code>.xdb_5gcp.rui.BaseResult base_result = 1;</code>
     */
    public Builder setBaseResult(com.innowireless.xdb5gcp.rui.BaseResult value) {
      if (baseResultBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        baseResult_ = value;
        onChanged();
      } else {
        baseResultBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.xdb_5gcp.rui.BaseResult base_result = 1;</code>
     */
    public Builder setBaseResult(
        com.innowireless.xdb5gcp.rui.BaseResult.Builder builderForValue) {
      if (baseResultBuilder_ == null) {
        baseResult_ = builderForValue.build();
        onChanged();
      } else {
        baseResultBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.xdb_5gcp.rui.BaseResult base_result = 1;</code>
     */
    public Builder mergeBaseResult(com.innowireless.xdb5gcp.rui.BaseResult value) {
      if (baseResultBuilder_ == null) {
        if (baseResult_ != null) {
          baseResult_ =
            com.innowireless.xdb5gcp.rui.BaseResult.newBuilder(baseResult_).mergeFrom(value).buildPartial();
        } else {
          baseResult_ = value;
        }
        onChanged();
      } else {
        baseResultBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.xdb_5gcp.rui.BaseResult base_result = 1;</code>
     */
    public Builder clearBaseResult() {
      if (baseResultBuilder_ == null) {
        baseResult_ = null;
        onChanged();
      } else {
        baseResult_ = null;
        baseResultBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.xdb_5gcp.rui.BaseResult base_result = 1;</code>
     */
    public com.innowireless.xdb5gcp.rui.BaseResult.Builder getBaseResultBuilder() {
      
      onChanged();
      return getBaseResultFieldBuilder().getBuilder();
    }
    /**
     * <code>.xdb_5gcp.rui.BaseResult base_result = 1;</code>
     */
    public com.innowireless.xdb5gcp.rui.BaseResultOrBuilder getBaseResultOrBuilder() {
      if (baseResultBuilder_ != null) {
        return baseResultBuilder_.getMessageOrBuilder();
      } else {
        return baseResult_ == null ?
            com.innowireless.xdb5gcp.rui.BaseResult.getDefaultInstance() : baseResult_;
      }
    }
    /**
     * <code>.xdb_5gcp.rui.BaseResult base_result = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.innowireless.xdb5gcp.rui.BaseResult, com.innowireless.xdb5gcp.rui.BaseResult.Builder, com.innowireless.xdb5gcp.rui.BaseResultOrBuilder> 
        getBaseResultFieldBuilder() {
      if (baseResultBuilder_ == null) {
        baseResultBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.innowireless.xdb5gcp.rui.BaseResult, com.innowireless.xdb5gcp.rui.BaseResult.Builder, com.innowireless.xdb5gcp.rui.BaseResultOrBuilder>(
                getBaseResult(),
                getParentForChildren(),
                isClean());
        baseResult_ = null;
      }
      return baseResultBuilder_;
    }

    private int sqlType_ = 0;
    /**
     * <code>.xdb_5gcp.rui.SqlType sql_type = 2;</code>
     */
    public int getSqlTypeValue() {
      return sqlType_;
    }
    /**
     * <code>.xdb_5gcp.rui.SqlType sql_type = 2;</code>
     */
    public Builder setSqlTypeValue(int value) {
      sqlType_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>.xdb_5gcp.rui.SqlType sql_type = 2;</code>
     */
    public com.innowireless.xdb5gcp.rui.SqlType getSqlType() {
      com.innowireless.xdb5gcp.rui.SqlType result = com.innowireless.xdb5gcp.rui.SqlType.valueOf(sqlType_);
      return result == null ? com.innowireless.xdb5gcp.rui.SqlType.UNRECOGNIZED : result;
    }
    /**
     * <code>.xdb_5gcp.rui.SqlType sql_type = 2;</code>
     */
    public Builder setSqlType(com.innowireless.xdb5gcp.rui.SqlType value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      sqlType_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.xdb_5gcp.rui.SqlType sql_type = 2;</code>
     */
    public Builder clearSqlType() {
      
      sqlType_ = 0;
      onChanged();
      return this;
    }

    private int executionStatus_ = 0;
    /**
     * <code>.xdb_5gcp.rui.ExecutionResult.ExecutionStatus execution_status = 3;</code>
     */
    public int getExecutionStatusValue() {
      return executionStatus_;
    }
    /**
     * <code>.xdb_5gcp.rui.ExecutionResult.ExecutionStatus execution_status = 3;</code>
     */
    public Builder setExecutionStatusValue(int value) {
      executionStatus_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>.xdb_5gcp.rui.ExecutionResult.ExecutionStatus execution_status = 3;</code>
     */
    public com.innowireless.xdb5gcp.rui.ExecutionResult.ExecutionStatus getExecutionStatus() {
      com.innowireless.xdb5gcp.rui.ExecutionResult.ExecutionStatus result = com.innowireless.xdb5gcp.rui.ExecutionResult.ExecutionStatus.valueOf(executionStatus_);
      return result == null ? com.innowireless.xdb5gcp.rui.ExecutionResult.ExecutionStatus.UNRECOGNIZED : result;
    }
    /**
     * <code>.xdb_5gcp.rui.ExecutionResult.ExecutionStatus execution_status = 3;</code>
     */
    public Builder setExecutionStatus(com.innowireless.xdb5gcp.rui.ExecutionResult.ExecutionStatus value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      executionStatus_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.xdb_5gcp.rui.ExecutionResult.ExecutionStatus execution_status = 3;</code>
     */
    public Builder clearExecutionStatus() {
      
      executionStatus_ = 0;
      onChanged();
      return this;
    }

    private int executionErrorCode_ = 0;
    /**
     * <code>.xdb_5gcp.rui.ExecutionResult.ExecutionErrorCode execution_error_code = 4;</code>
     */
    public int getExecutionErrorCodeValue() {
      return executionErrorCode_;
    }
    /**
     * <code>.xdb_5gcp.rui.ExecutionResult.ExecutionErrorCode execution_error_code = 4;</code>
     */
    public Builder setExecutionErrorCodeValue(int value) {
      executionErrorCode_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>.xdb_5gcp.rui.ExecutionResult.ExecutionErrorCode execution_error_code = 4;</code>
     */
    public com.innowireless.xdb5gcp.rui.ExecutionResult.ExecutionErrorCode getExecutionErrorCode() {
      com.innowireless.xdb5gcp.rui.ExecutionResult.ExecutionErrorCode result = com.innowireless.xdb5gcp.rui.ExecutionResult.ExecutionErrorCode.valueOf(executionErrorCode_);
      return result == null ? com.innowireless.xdb5gcp.rui.ExecutionResult.ExecutionErrorCode.UNRECOGNIZED : result;
    }
    /**
     * <code>.xdb_5gcp.rui.ExecutionResult.ExecutionErrorCode execution_error_code = 4;</code>
     */
    public Builder setExecutionErrorCode(com.innowireless.xdb5gcp.rui.ExecutionResult.ExecutionErrorCode value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      executionErrorCode_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.xdb_5gcp.rui.ExecutionResult.ExecutionErrorCode execution_error_code = 4;</code>
     */
    public Builder clearExecutionErrorCode() {
      
      executionErrorCode_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object executionMessage_ = "";
    /**
     * <code>string execution_message = 5;</code>
     */
    public java.lang.String getExecutionMessage() {
      java.lang.Object ref = executionMessage_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        executionMessage_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string execution_message = 5;</code>
     */
    public com.google.protobuf.ByteString
        getExecutionMessageBytes() {
      java.lang.Object ref = executionMessage_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        executionMessage_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string execution_message = 5;</code>
     */
    public Builder setExecutionMessage(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      executionMessage_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string execution_message = 5;</code>
     */
    public Builder clearExecutionMessage() {
      
      executionMessage_ = getDefaultInstance().getExecutionMessage();
      onChanged();
      return this;
    }
    /**
     * <code>string execution_message = 5;</code>
     */
    public Builder setExecutionMessageBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      executionMessage_ = value;
      onChanged();
      return this;
    }

    private long executionTime_ ;
    /**
     * <pre>
     * milliseconds
     * </pre>
     *
     * <code>int64 execution_time = 6;</code>
     */
    public long getExecutionTime() {
      return executionTime_;
    }
    /**
     * <pre>
     * milliseconds
     * </pre>
     *
     * <code>int64 execution_time = 6;</code>
     */
    public Builder setExecutionTime(long value) {
      
      executionTime_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * milliseconds
     * </pre>
     *
     * <code>int64 execution_time = 6;</code>
     */
    public Builder clearExecutionTime() {
      
      executionTime_ = 0L;
      onChanged();
      return this;
    }

    private long resultRowCount_ ;
    /**
     * <code>int64 result_row_count = 7;</code>
     */
    public long getResultRowCount() {
      return resultRowCount_;
    }
    /**
     * <code>int64 result_row_count = 7;</code>
     */
    public Builder setResultRowCount(long value) {
      
      resultRowCount_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int64 result_row_count = 7;</code>
     */
    public Builder clearResultRowCount() {
      
      resultRowCount_ = 0L;
      onChanged();
      return this;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:xdb_5gcp.rui.ExecutionResult)
  }

  // @@protoc_insertion_point(class_scope:xdb_5gcp.rui.ExecutionResult)
  private static final com.innowireless.xdb5gcp.rui.ExecutionResult DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.innowireless.xdb5gcp.rui.ExecutionResult();
  }

  public static com.innowireless.xdb5gcp.rui.ExecutionResult getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ExecutionResult>
      PARSER = new com.google.protobuf.AbstractParser<ExecutionResult>() {
    public ExecutionResult parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new ExecutionResult(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<ExecutionResult> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ExecutionResult> getParserForType() {
    return PARSER;
  }

  public com.innowireless.xdb5gcp.rui.ExecutionResult getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

