// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: xdb_5gcp_rui.proto

package com.innowireless.xdb5gcp.rui;

public interface GenerateResultOrBuilder extends
    // @@protoc_insertion_point(interface_extends:xdb_5gcp.rui.GenerateResult)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.xdb_5gcp.rui.BaseResult base_result = 1;</code>
   */
  boolean hasBaseResult();
  /**
   * <code>.xdb_5gcp.rui.BaseResult base_result = 1;</code>
   */
  com.innowireless.xdb5gcp.rui.BaseResult getBaseResult();
  /**
   * <code>.xdb_5gcp.rui.BaseResult base_result = 1;</code>
   */
  com.innowireless.xdb5gcp.rui.BaseResultOrBuilder getBaseResultOrBuilder();

  /**
   * <code>.xdb_5gcp.rui.Key key = 2;</code>
   */
  boolean hasKey();
  /**
   * <code>.xdb_5gcp.rui.Key key = 2;</code>
   */
  com.innowireless.xdb5gcp.rui.Key getKey();
  /**
   * <code>.xdb_5gcp.rui.Key key = 2;</code>
   */
  com.innowireless.xdb5gcp.rui.KeyOrBuilder getKeyOrBuilder();

  /**
   * <code>.xdb_5gcp.rui.SqlType sql_type = 3;</code>
   */
  int getSqlTypeValue();
  /**
   * <code>.xdb_5gcp.rui.SqlType sql_type = 3;</code>
   */
  com.innowireless.xdb5gcp.rui.SqlType getSqlType();
}
