// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: xdb_5gcp_rui.proto

package com.innowireless.xdb5gcp.rui;

/**
 * Protobuf type {@code xdb_5gcp.rui.GenerateResult}
 */
public  final class GenerateResult extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:xdb_5gcp.rui.GenerateResult)
    GenerateResultOrBuilder {
private static final long serialVersionUID = 0L;
  // Use GenerateResult.newBuilder() to construct.
  private GenerateResult(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private GenerateResult() {
    sqlType_ = 0;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private GenerateResult(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            com.innowireless.xdb5gcp.rui.BaseResult.Builder subBuilder = null;
            if (baseResult_ != null) {
              subBuilder = baseResult_.toBuilder();
            }
            baseResult_ = input.readMessage(com.innowireless.xdb5gcp.rui.BaseResult.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(baseResult_);
              baseResult_ = subBuilder.buildPartial();
            }

            break;
          }
          case 18: {
            com.innowireless.xdb5gcp.rui.Key.Builder subBuilder = null;
            if (key_ != null) {
              subBuilder = key_.toBuilder();
            }
            key_ = input.readMessage(com.innowireless.xdb5gcp.rui.Key.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(key_);
              key_ = subBuilder.buildPartial();
            }

            break;
          }
          case 24: {
            int rawValue = input.readEnum();

            sqlType_ = rawValue;
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.innowireless.xdb5gcp.rui.RuiProto.internal_static_xdb_5gcp_rui_GenerateResult_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.innowireless.xdb5gcp.rui.RuiProto.internal_static_xdb_5gcp_rui_GenerateResult_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.innowireless.xdb5gcp.rui.GenerateResult.class, com.innowireless.xdb5gcp.rui.GenerateResult.Builder.class);
  }

  public static final int BASE_RESULT_FIELD_NUMBER = 1;
  private com.innowireless.xdb5gcp.rui.BaseResult baseResult_;
  /**
   * <code>.xdb_5gcp.rui.BaseResult base_result = 1;</code>
   */
  public boolean hasBaseResult() {
    return baseResult_ != null;
  }
  /**
   * <code>.xdb_5gcp.rui.BaseResult base_result = 1;</code>
   */
  public com.innowireless.xdb5gcp.rui.BaseResult getBaseResult() {
    return baseResult_ == null ? com.innowireless.xdb5gcp.rui.BaseResult.getDefaultInstance() : baseResult_;
  }
  /**
   * <code>.xdb_5gcp.rui.BaseResult base_result = 1;</code>
   */
  public com.innowireless.xdb5gcp.rui.BaseResultOrBuilder getBaseResultOrBuilder() {
    return getBaseResult();
  }

  public static final int KEY_FIELD_NUMBER = 2;
  private com.innowireless.xdb5gcp.rui.Key key_;
  /**
   * <code>.xdb_5gcp.rui.Key key = 2;</code>
   */
  public boolean hasKey() {
    return key_ != null;
  }
  /**
   * <code>.xdb_5gcp.rui.Key key = 2;</code>
   */
  public com.innowireless.xdb5gcp.rui.Key getKey() {
    return key_ == null ? com.innowireless.xdb5gcp.rui.Key.getDefaultInstance() : key_;
  }
  /**
   * <code>.xdb_5gcp.rui.Key key = 2;</code>
   */
  public com.innowireless.xdb5gcp.rui.KeyOrBuilder getKeyOrBuilder() {
    return getKey();
  }

  public static final int SQL_TYPE_FIELD_NUMBER = 3;
  private int sqlType_;
  /**
   * <code>.xdb_5gcp.rui.SqlType sql_type = 3;</code>
   */
  public int getSqlTypeValue() {
    return sqlType_;
  }
  /**
   * <code>.xdb_5gcp.rui.SqlType sql_type = 3;</code>
   */
  public com.innowireless.xdb5gcp.rui.SqlType getSqlType() {
    com.innowireless.xdb5gcp.rui.SqlType result = com.innowireless.xdb5gcp.rui.SqlType.valueOf(sqlType_);
    return result == null ? com.innowireless.xdb5gcp.rui.SqlType.UNRECOGNIZED : result;
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (baseResult_ != null) {
      output.writeMessage(1, getBaseResult());
    }
    if (key_ != null) {
      output.writeMessage(2, getKey());
    }
    if (sqlType_ != com.innowireless.xdb5gcp.rui.SqlType.SELECT_STMT.getNumber()) {
      output.writeEnum(3, sqlType_);
    }
    unknownFields.writeTo(output);
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (baseResult_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getBaseResult());
    }
    if (key_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getKey());
    }
    if (sqlType_ != com.innowireless.xdb5gcp.rui.SqlType.SELECT_STMT.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(3, sqlType_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.innowireless.xdb5gcp.rui.GenerateResult)) {
      return super.equals(obj);
    }
    com.innowireless.xdb5gcp.rui.GenerateResult other = (com.innowireless.xdb5gcp.rui.GenerateResult) obj;

    boolean result = true;
    result = result && (hasBaseResult() == other.hasBaseResult());
    if (hasBaseResult()) {
      result = result && getBaseResult()
          .equals(other.getBaseResult());
    }
    result = result && (hasKey() == other.hasKey());
    if (hasKey()) {
      result = result && getKey()
          .equals(other.getKey());
    }
    result = result && sqlType_ == other.sqlType_;
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasBaseResult()) {
      hash = (37 * hash) + BASE_RESULT_FIELD_NUMBER;
      hash = (53 * hash) + getBaseResult().hashCode();
    }
    if (hasKey()) {
      hash = (37 * hash) + KEY_FIELD_NUMBER;
      hash = (53 * hash) + getKey().hashCode();
    }
    hash = (37 * hash) + SQL_TYPE_FIELD_NUMBER;
    hash = (53 * hash) + sqlType_;
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.innowireless.xdb5gcp.rui.GenerateResult parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.innowireless.xdb5gcp.rui.GenerateResult parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.innowireless.xdb5gcp.rui.GenerateResult parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.innowireless.xdb5gcp.rui.GenerateResult parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.innowireless.xdb5gcp.rui.GenerateResult parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.innowireless.xdb5gcp.rui.GenerateResult parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.innowireless.xdb5gcp.rui.GenerateResult parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.innowireless.xdb5gcp.rui.GenerateResult parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.innowireless.xdb5gcp.rui.GenerateResult parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.innowireless.xdb5gcp.rui.GenerateResult parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.innowireless.xdb5gcp.rui.GenerateResult parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.innowireless.xdb5gcp.rui.GenerateResult parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.innowireless.xdb5gcp.rui.GenerateResult prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code xdb_5gcp.rui.GenerateResult}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:xdb_5gcp.rui.GenerateResult)
      com.innowireless.xdb5gcp.rui.GenerateResultOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.innowireless.xdb5gcp.rui.RuiProto.internal_static_xdb_5gcp_rui_GenerateResult_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.innowireless.xdb5gcp.rui.RuiProto.internal_static_xdb_5gcp_rui_GenerateResult_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.innowireless.xdb5gcp.rui.GenerateResult.class, com.innowireless.xdb5gcp.rui.GenerateResult.Builder.class);
    }

    // Construct using com.innowireless.xdb5gcp.rui.GenerateResult.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      if (baseResultBuilder_ == null) {
        baseResult_ = null;
      } else {
        baseResult_ = null;
        baseResultBuilder_ = null;
      }
      if (keyBuilder_ == null) {
        key_ = null;
      } else {
        key_ = null;
        keyBuilder_ = null;
      }
      sqlType_ = 0;

      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.innowireless.xdb5gcp.rui.RuiProto.internal_static_xdb_5gcp_rui_GenerateResult_descriptor;
    }

    public com.innowireless.xdb5gcp.rui.GenerateResult getDefaultInstanceForType() {
      return com.innowireless.xdb5gcp.rui.GenerateResult.getDefaultInstance();
    }

    public com.innowireless.xdb5gcp.rui.GenerateResult build() {
      com.innowireless.xdb5gcp.rui.GenerateResult result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public com.innowireless.xdb5gcp.rui.GenerateResult buildPartial() {
      com.innowireless.xdb5gcp.rui.GenerateResult result = new com.innowireless.xdb5gcp.rui.GenerateResult(this);
      if (baseResultBuilder_ == null) {
        result.baseResult_ = baseResult_;
      } else {
        result.baseResult_ = baseResultBuilder_.build();
      }
      if (keyBuilder_ == null) {
        result.key_ = key_;
      } else {
        result.key_ = keyBuilder_.build();
      }
      result.sqlType_ = sqlType_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.innowireless.xdb5gcp.rui.GenerateResult) {
        return mergeFrom((com.innowireless.xdb5gcp.rui.GenerateResult)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.innowireless.xdb5gcp.rui.GenerateResult other) {
      if (other == com.innowireless.xdb5gcp.rui.GenerateResult.getDefaultInstance()) return this;
      if (other.hasBaseResult()) {
        mergeBaseResult(other.getBaseResult());
      }
      if (other.hasKey()) {
        mergeKey(other.getKey());
      }
      if (other.sqlType_ != 0) {
        setSqlTypeValue(other.getSqlTypeValue());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.innowireless.xdb5gcp.rui.GenerateResult parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.innowireless.xdb5gcp.rui.GenerateResult) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private com.innowireless.xdb5gcp.rui.BaseResult baseResult_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.innowireless.xdb5gcp.rui.BaseResult, com.innowireless.xdb5gcp.rui.BaseResult.Builder, com.innowireless.xdb5gcp.rui.BaseResultOrBuilder> baseResultBuilder_;
    /**
     * <code>.xdb_5gcp.rui.BaseResult base_result = 1;</code>
     */
    public boolean hasBaseResult() {
      return baseResultBuilder_ != null || baseResult_ != null;
    }
    /**
     * <code>.xdb_5gcp.rui.BaseResult base_result = 1;</code>
     */
    public com.innowireless.xdb5gcp.rui.BaseResult getBaseResult() {
      if (baseResultBuilder_ == null) {
        return baseResult_ == null ? com.innowireless.xdb5gcp.rui.BaseResult.getDefaultInstance() : baseResult_;
      } else {
        return baseResultBuilder_.getMessage();
      }
    }
    /**
     * <code>.xdb_5gcp.rui.BaseResult base_result = 1;</code>
     */
    public Builder setBaseResult(com.innowireless.xdb5gcp.rui.BaseResult value) {
      if (baseResultBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        baseResult_ = value;
        onChanged();
      } else {
        baseResultBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.xdb_5gcp.rui.BaseResult base_result = 1;</code>
     */
    public Builder setBaseResult(
        com.innowireless.xdb5gcp.rui.BaseResult.Builder builderForValue) {
      if (baseResultBuilder_ == null) {
        baseResult_ = builderForValue.build();
        onChanged();
      } else {
        baseResultBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.xdb_5gcp.rui.BaseResult base_result = 1;</code>
     */
    public Builder mergeBaseResult(com.innowireless.xdb5gcp.rui.BaseResult value) {
      if (baseResultBuilder_ == null) {
        if (baseResult_ != null) {
          baseResult_ =
            com.innowireless.xdb5gcp.rui.BaseResult.newBuilder(baseResult_).mergeFrom(value).buildPartial();
        } else {
          baseResult_ = value;
        }
        onChanged();
      } else {
        baseResultBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.xdb_5gcp.rui.BaseResult base_result = 1;</code>
     */
    public Builder clearBaseResult() {
      if (baseResultBuilder_ == null) {
        baseResult_ = null;
        onChanged();
      } else {
        baseResult_ = null;
        baseResultBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.xdb_5gcp.rui.BaseResult base_result = 1;</code>
     */
    public com.innowireless.xdb5gcp.rui.BaseResult.Builder getBaseResultBuilder() {
      
      onChanged();
      return getBaseResultFieldBuilder().getBuilder();
    }
    /**
     * <code>.xdb_5gcp.rui.BaseResult base_result = 1;</code>
     */
    public com.innowireless.xdb5gcp.rui.BaseResultOrBuilder getBaseResultOrBuilder() {
      if (baseResultBuilder_ != null) {
        return baseResultBuilder_.getMessageOrBuilder();
      } else {
        return baseResult_ == null ?
            com.innowireless.xdb5gcp.rui.BaseResult.getDefaultInstance() : baseResult_;
      }
    }
    /**
     * <code>.xdb_5gcp.rui.BaseResult base_result = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.innowireless.xdb5gcp.rui.BaseResult, com.innowireless.xdb5gcp.rui.BaseResult.Builder, com.innowireless.xdb5gcp.rui.BaseResultOrBuilder> 
        getBaseResultFieldBuilder() {
      if (baseResultBuilder_ == null) {
        baseResultBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.innowireless.xdb5gcp.rui.BaseResult, com.innowireless.xdb5gcp.rui.BaseResult.Builder, com.innowireless.xdb5gcp.rui.BaseResultOrBuilder>(
                getBaseResult(),
                getParentForChildren(),
                isClean());
        baseResult_ = null;
      }
      return baseResultBuilder_;
    }

    private com.innowireless.xdb5gcp.rui.Key key_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.innowireless.xdb5gcp.rui.Key, com.innowireless.xdb5gcp.rui.Key.Builder, com.innowireless.xdb5gcp.rui.KeyOrBuilder> keyBuilder_;
    /**
     * <code>.xdb_5gcp.rui.Key key = 2;</code>
     */
    public boolean hasKey() {
      return keyBuilder_ != null || key_ != null;
    }
    /**
     * <code>.xdb_5gcp.rui.Key key = 2;</code>
     */
    public com.innowireless.xdb5gcp.rui.Key getKey() {
      if (keyBuilder_ == null) {
        return key_ == null ? com.innowireless.xdb5gcp.rui.Key.getDefaultInstance() : key_;
      } else {
        return keyBuilder_.getMessage();
      }
    }
    /**
     * <code>.xdb_5gcp.rui.Key key = 2;</code>
     */
    public Builder setKey(com.innowireless.xdb5gcp.rui.Key value) {
      if (keyBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        key_ = value;
        onChanged();
      } else {
        keyBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.xdb_5gcp.rui.Key key = 2;</code>
     */
    public Builder setKey(
        com.innowireless.xdb5gcp.rui.Key.Builder builderForValue) {
      if (keyBuilder_ == null) {
        key_ = builderForValue.build();
        onChanged();
      } else {
        keyBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.xdb_5gcp.rui.Key key = 2;</code>
     */
    public Builder mergeKey(com.innowireless.xdb5gcp.rui.Key value) {
      if (keyBuilder_ == null) {
        if (key_ != null) {
          key_ =
            com.innowireless.xdb5gcp.rui.Key.newBuilder(key_).mergeFrom(value).buildPartial();
        } else {
          key_ = value;
        }
        onChanged();
      } else {
        keyBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.xdb_5gcp.rui.Key key = 2;</code>
     */
    public Builder clearKey() {
      if (keyBuilder_ == null) {
        key_ = null;
        onChanged();
      } else {
        key_ = null;
        keyBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.xdb_5gcp.rui.Key key = 2;</code>
     */
    public com.innowireless.xdb5gcp.rui.Key.Builder getKeyBuilder() {
      
      onChanged();
      return getKeyFieldBuilder().getBuilder();
    }
    /**
     * <code>.xdb_5gcp.rui.Key key = 2;</code>
     */
    public com.innowireless.xdb5gcp.rui.KeyOrBuilder getKeyOrBuilder() {
      if (keyBuilder_ != null) {
        return keyBuilder_.getMessageOrBuilder();
      } else {
        return key_ == null ?
            com.innowireless.xdb5gcp.rui.Key.getDefaultInstance() : key_;
      }
    }
    /**
     * <code>.xdb_5gcp.rui.Key key = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.innowireless.xdb5gcp.rui.Key, com.innowireless.xdb5gcp.rui.Key.Builder, com.innowireless.xdb5gcp.rui.KeyOrBuilder> 
        getKeyFieldBuilder() {
      if (keyBuilder_ == null) {
        keyBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.innowireless.xdb5gcp.rui.Key, com.innowireless.xdb5gcp.rui.Key.Builder, com.innowireless.xdb5gcp.rui.KeyOrBuilder>(
                getKey(),
                getParentForChildren(),
                isClean());
        key_ = null;
      }
      return keyBuilder_;
    }

    private int sqlType_ = 0;
    /**
     * <code>.xdb_5gcp.rui.SqlType sql_type = 3;</code>
     */
    public int getSqlTypeValue() {
      return sqlType_;
    }
    /**
     * <code>.xdb_5gcp.rui.SqlType sql_type = 3;</code>
     */
    public Builder setSqlTypeValue(int value) {
      sqlType_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>.xdb_5gcp.rui.SqlType sql_type = 3;</code>
     */
    public com.innowireless.xdb5gcp.rui.SqlType getSqlType() {
      com.innowireless.xdb5gcp.rui.SqlType result = com.innowireless.xdb5gcp.rui.SqlType.valueOf(sqlType_);
      return result == null ? com.innowireless.xdb5gcp.rui.SqlType.UNRECOGNIZED : result;
    }
    /**
     * <code>.xdb_5gcp.rui.SqlType sql_type = 3;</code>
     */
    public Builder setSqlType(com.innowireless.xdb5gcp.rui.SqlType value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      sqlType_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.xdb_5gcp.rui.SqlType sql_type = 3;</code>
     */
    public Builder clearSqlType() {
      
      sqlType_ = 0;
      onChanged();
      return this;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:xdb_5gcp.rui.GenerateResult)
  }

  // @@protoc_insertion_point(class_scope:xdb_5gcp.rui.GenerateResult)
  private static final com.innowireless.xdb5gcp.rui.GenerateResult DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.innowireless.xdb5gcp.rui.GenerateResult();
  }

  public static com.innowireless.xdb5gcp.rui.GenerateResult getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<GenerateResult>
      PARSER = new com.google.protobuf.AbstractParser<GenerateResult>() {
    public GenerateResult parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new GenerateResult(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<GenerateResult> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<GenerateResult> getParserForType() {
    return PARSER;
  }

  public com.innowireless.xdb5gcp.rui.GenerateResult getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

