// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: xdb_5gcp_rui.proto

package com.innowireless.xdb5gcp.rui;

public interface KeyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:xdb_5gcp.rui.Key)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string key_string = 1;</code>
   */
  java.lang.String getKeyString();
  /**
   * <code>string key_string = 1;</code>
   */
  com.google.protobuf.ByteString
      getKeyStringBytes();
}
