// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: xdb_5gcp_rui.proto

package com.innowireless.xdb5gcp.rui;

/**
 * Protobuf type {@code xdb_5gcp.rui.QueryRequest}
 */
public  final class QueryRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:xdb_5gcp.rui.QueryRequest)
    QueryRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use QueryRequest.newBuilder() to construct.
  private QueryRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private QueryRequest() {
    userIdentity_ = "";
    sqlString_ = "";
    startTimestamp_ = 0L;
    endTimestamp_ = 0L;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private QueryRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            userIdentity_ = s;
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            sqlString_ = s;
            break;
          }
          case 24: {

            startTimestamp_ = input.readInt64();
            break;
          }
          case 32: {

            endTimestamp_ = input.readInt64();
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.innowireless.xdb5gcp.rui.RuiProto.internal_static_xdb_5gcp_rui_QueryRequest_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.innowireless.xdb5gcp.rui.RuiProto.internal_static_xdb_5gcp_rui_QueryRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.innowireless.xdb5gcp.rui.QueryRequest.class, com.innowireless.xdb5gcp.rui.QueryRequest.Builder.class);
  }

  public static final int USER_IDENTITY_FIELD_NUMBER = 1;
  private volatile java.lang.Object userIdentity_;
  /**
   * <code>string user_identity = 1;</code>
   */
  public java.lang.String getUserIdentity() {
    java.lang.Object ref = userIdentity_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      userIdentity_ = s;
      return s;
    }
  }
  /**
   * <code>string user_identity = 1;</code>
   */
  public com.google.protobuf.ByteString
      getUserIdentityBytes() {
    java.lang.Object ref = userIdentity_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      userIdentity_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int SQL_STRING_FIELD_NUMBER = 2;
  private volatile java.lang.Object sqlString_;
  /**
   * <code>string sql_string = 2;</code>
   */
  public java.lang.String getSqlString() {
    java.lang.Object ref = sqlString_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      sqlString_ = s;
      return s;
    }
  }
  /**
   * <code>string sql_string = 2;</code>
   */
  public com.google.protobuf.ByteString
      getSqlStringBytes() {
    java.lang.Object ref = sqlString_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      sqlString_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int START_TIMESTAMP_FIELD_NUMBER = 3;
  private long startTimestamp_;
  /**
   * <pre>
   * start timestamp for ISA_HUB table
   * </pre>
   *
   * <code>int64 start_timestamp = 3;</code>
   */
  public long getStartTimestamp() {
    return startTimestamp_;
  }

  public static final int END_TIMESTAMP_FIELD_NUMBER = 4;
  private long endTimestamp_;
  /**
   * <pre>
   * end timestamp for ISA_HUB table
   * </pre>
   *
   * <code>int64 end_timestamp = 4;</code>
   */
  public long getEndTimestamp() {
    return endTimestamp_;
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getUserIdentityBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, userIdentity_);
    }
    if (!getSqlStringBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, sqlString_);
    }
    if (startTimestamp_ != 0L) {
      output.writeInt64(3, startTimestamp_);
    }
    if (endTimestamp_ != 0L) {
      output.writeInt64(4, endTimestamp_);
    }
    unknownFields.writeTo(output);
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getUserIdentityBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, userIdentity_);
    }
    if (!getSqlStringBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, sqlString_);
    }
    if (startTimestamp_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(3, startTimestamp_);
    }
    if (endTimestamp_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(4, endTimestamp_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.innowireless.xdb5gcp.rui.QueryRequest)) {
      return super.equals(obj);
    }
    com.innowireless.xdb5gcp.rui.QueryRequest other = (com.innowireless.xdb5gcp.rui.QueryRequest) obj;

    boolean result = true;
    result = result && getUserIdentity()
        .equals(other.getUserIdentity());
    result = result && getSqlString()
        .equals(other.getSqlString());
    result = result && (getStartTimestamp()
        == other.getStartTimestamp());
    result = result && (getEndTimestamp()
        == other.getEndTimestamp());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + USER_IDENTITY_FIELD_NUMBER;
    hash = (53 * hash) + getUserIdentity().hashCode();
    hash = (37 * hash) + SQL_STRING_FIELD_NUMBER;
    hash = (53 * hash) + getSqlString().hashCode();
    hash = (37 * hash) + START_TIMESTAMP_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getStartTimestamp());
    hash = (37 * hash) + END_TIMESTAMP_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getEndTimestamp());
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.innowireless.xdb5gcp.rui.QueryRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.innowireless.xdb5gcp.rui.QueryRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.innowireless.xdb5gcp.rui.QueryRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.innowireless.xdb5gcp.rui.QueryRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.innowireless.xdb5gcp.rui.QueryRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.innowireless.xdb5gcp.rui.QueryRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.innowireless.xdb5gcp.rui.QueryRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.innowireless.xdb5gcp.rui.QueryRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.innowireless.xdb5gcp.rui.QueryRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.innowireless.xdb5gcp.rui.QueryRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.innowireless.xdb5gcp.rui.QueryRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.innowireless.xdb5gcp.rui.QueryRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.innowireless.xdb5gcp.rui.QueryRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code xdb_5gcp.rui.QueryRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:xdb_5gcp.rui.QueryRequest)
      com.innowireless.xdb5gcp.rui.QueryRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.innowireless.xdb5gcp.rui.RuiProto.internal_static_xdb_5gcp_rui_QueryRequest_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.innowireless.xdb5gcp.rui.RuiProto.internal_static_xdb_5gcp_rui_QueryRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.innowireless.xdb5gcp.rui.QueryRequest.class, com.innowireless.xdb5gcp.rui.QueryRequest.Builder.class);
    }

    // Construct using com.innowireless.xdb5gcp.rui.QueryRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      userIdentity_ = "";

      sqlString_ = "";

      startTimestamp_ = 0L;

      endTimestamp_ = 0L;

      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.innowireless.xdb5gcp.rui.RuiProto.internal_static_xdb_5gcp_rui_QueryRequest_descriptor;
    }

    public com.innowireless.xdb5gcp.rui.QueryRequest getDefaultInstanceForType() {
      return com.innowireless.xdb5gcp.rui.QueryRequest.getDefaultInstance();
    }

    public com.innowireless.xdb5gcp.rui.QueryRequest build() {
      com.innowireless.xdb5gcp.rui.QueryRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public com.innowireless.xdb5gcp.rui.QueryRequest buildPartial() {
      com.innowireless.xdb5gcp.rui.QueryRequest result = new com.innowireless.xdb5gcp.rui.QueryRequest(this);
      result.userIdentity_ = userIdentity_;
      result.sqlString_ = sqlString_;
      result.startTimestamp_ = startTimestamp_;
      result.endTimestamp_ = endTimestamp_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.innowireless.xdb5gcp.rui.QueryRequest) {
        return mergeFrom((com.innowireless.xdb5gcp.rui.QueryRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.innowireless.xdb5gcp.rui.QueryRequest other) {
      if (other == com.innowireless.xdb5gcp.rui.QueryRequest.getDefaultInstance()) return this;
      if (!other.getUserIdentity().isEmpty()) {
        userIdentity_ = other.userIdentity_;
        onChanged();
      }
      if (!other.getSqlString().isEmpty()) {
        sqlString_ = other.sqlString_;
        onChanged();
      }
      if (other.getStartTimestamp() != 0L) {
        setStartTimestamp(other.getStartTimestamp());
      }
      if (other.getEndTimestamp() != 0L) {
        setEndTimestamp(other.getEndTimestamp());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.innowireless.xdb5gcp.rui.QueryRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.innowireless.xdb5gcp.rui.QueryRequest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object userIdentity_ = "";
    /**
     * <code>string user_identity = 1;</code>
     */
    public java.lang.String getUserIdentity() {
      java.lang.Object ref = userIdentity_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        userIdentity_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string user_identity = 1;</code>
     */
    public com.google.protobuf.ByteString
        getUserIdentityBytes() {
      java.lang.Object ref = userIdentity_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        userIdentity_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string user_identity = 1;</code>
     */
    public Builder setUserIdentity(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      userIdentity_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string user_identity = 1;</code>
     */
    public Builder clearUserIdentity() {
      
      userIdentity_ = getDefaultInstance().getUserIdentity();
      onChanged();
      return this;
    }
    /**
     * <code>string user_identity = 1;</code>
     */
    public Builder setUserIdentityBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      userIdentity_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object sqlString_ = "";
    /**
     * <code>string sql_string = 2;</code>
     */
    public java.lang.String getSqlString() {
      java.lang.Object ref = sqlString_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        sqlString_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string sql_string = 2;</code>
     */
    public com.google.protobuf.ByteString
        getSqlStringBytes() {
      java.lang.Object ref = sqlString_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        sqlString_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string sql_string = 2;</code>
     */
    public Builder setSqlString(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      sqlString_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string sql_string = 2;</code>
     */
    public Builder clearSqlString() {
      
      sqlString_ = getDefaultInstance().getSqlString();
      onChanged();
      return this;
    }
    /**
     * <code>string sql_string = 2;</code>
     */
    public Builder setSqlStringBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      sqlString_ = value;
      onChanged();
      return this;
    }

    private long startTimestamp_ ;
    /**
     * <pre>
     * start timestamp for ISA_HUB table
     * </pre>
     *
     * <code>int64 start_timestamp = 3;</code>
     */
    public long getStartTimestamp() {
      return startTimestamp_;
    }
    /**
     * <pre>
     * start timestamp for ISA_HUB table
     * </pre>
     *
     * <code>int64 start_timestamp = 3;</code>
     */
    public Builder setStartTimestamp(long value) {
      
      startTimestamp_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * start timestamp for ISA_HUB table
     * </pre>
     *
     * <code>int64 start_timestamp = 3;</code>
     */
    public Builder clearStartTimestamp() {
      
      startTimestamp_ = 0L;
      onChanged();
      return this;
    }

    private long endTimestamp_ ;
    /**
     * <pre>
     * end timestamp for ISA_HUB table
     * </pre>
     *
     * <code>int64 end_timestamp = 4;</code>
     */
    public long getEndTimestamp() {
      return endTimestamp_;
    }
    /**
     * <pre>
     * end timestamp for ISA_HUB table
     * </pre>
     *
     * <code>int64 end_timestamp = 4;</code>
     */
    public Builder setEndTimestamp(long value) {
      
      endTimestamp_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * end timestamp for ISA_HUB table
     * </pre>
     *
     * <code>int64 end_timestamp = 4;</code>
     */
    public Builder clearEndTimestamp() {
      
      endTimestamp_ = 0L;
      onChanged();
      return this;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:xdb_5gcp.rui.QueryRequest)
  }

  // @@protoc_insertion_point(class_scope:xdb_5gcp.rui.QueryRequest)
  private static final com.innowireless.xdb5gcp.rui.QueryRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.innowireless.xdb5gcp.rui.QueryRequest();
  }

  public static com.innowireless.xdb5gcp.rui.QueryRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<QueryRequest>
      PARSER = new com.google.protobuf.AbstractParser<QueryRequest>() {
    public QueryRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new QueryRequest(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<QueryRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<QueryRequest> getParserForType() {
    return PARSER;
  }

  public com.innowireless.xdb5gcp.rui.QueryRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

