// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: xdb_5gcp_rui.proto

package com.innowireless.xdb5gcp.rui;

public interface RemoveTimePartitionRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:xdb_5gcp.rui.RemoveTimePartitionRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string table_name = 1;</code>
   */
  java.lang.String getTableName();
  /**
   * <code>string table_name = 1;</code>
   */
  com.google.protobuf.ByteString
      getTableNameBytes();

  /**
   * <pre>
   * start date &lt;= target file &lt;= end date
   * currently, only date unit will be used
   * 2021-04-04T20:11:11 -&gt; 2021-04-04
   * </pre>
   *
   * <code>string start_datetime = 2;</code>
   */
  java.lang.String getStartDatetime();
  /**
   * <pre>
   * start date &lt;= target file &lt;= end date
   * currently, only date unit will be used
   * 2021-04-04T20:11:11 -&gt; 2021-04-04
   * </pre>
   *
   * <code>string start_datetime = 2;</code>
   */
  com.google.protobuf.ByteString
      getStartDatetimeBytes();

  /**
   * <pre>
   * local datetime format (YYYY-MM-DD)
   * </pre>
   *
   * <code>string end_datetime = 3;</code>
   */
  java.lang.String getEndDatetime();
  /**
   * <pre>
   * local datetime format (YYYY-MM-DD)
   * </pre>
   *
   * <code>string end_datetime = 3;</code>
   */
  com.google.protobuf.ByteString
      getEndDatetimeBytes();
}
