// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: xdb_5gcp_rui.proto

package com.innowireless.xdb5gcp.rui;

public interface TableInfoListResultOrBuilder extends
    // @@protoc_insertion_point(interface_extends:xdb_5gcp.rui.TableInfoListResult)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.xdb_5gcp.rui.BaseResult base_result = 1;</code>
   */
  boolean hasBaseResult();
  /**
   * <code>.xdb_5gcp.rui.BaseResult base_result = 1;</code>
   */
  com.innowireless.xdb5gcp.rui.BaseResult getBaseResult();
  /**
   * <code>.xdb_5gcp.rui.BaseResult base_result = 1;</code>
   */
  com.innowireless.xdb5gcp.rui.BaseResultOrBuilder getBaseResultOrBuilder();

  /**
   * <code>repeated .xdb_5gcp.rui.TableInfo table_info_list = 2;</code>
   */
  java.util.List<com.innowireless.xdb5gcp.rui.TableInfo> 
      getTableInfoListList();
  /**
   * <code>repeated .xdb_5gcp.rui.TableInfo table_info_list = 2;</code>
   */
  com.innowireless.xdb5gcp.rui.TableInfo getTableInfoList(int index);
  /**
   * <code>repeated .xdb_5gcp.rui.TableInfo table_info_list = 2;</code>
   */
  int getTableInfoListCount();
  /**
   * <code>repeated .xdb_5gcp.rui.TableInfo table_info_list = 2;</code>
   */
  java.util.List<? extends com.innowireless.xdb5gcp.rui.TableInfoOrBuilder> 
      getTableInfoListOrBuilderList();
  /**
   * <code>repeated .xdb_5gcp.rui.TableInfo table_info_list = 2;</code>
   */
  com.innowireless.xdb5gcp.rui.TableInfoOrBuilder getTableInfoListOrBuilder(
      int index);
}
