// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: xdb_5gcp_rui.proto

package com.innowireless.xdb5gcp.rui;

/**
 * Protobuf type {@code xdb_5gcp.rui.TableInfo}
 */
public  final class TableInfo extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:xdb_5gcp.rui.TableInfo)
    TableInfoOrBuilder {
private static final long serialVersionUID = 0L;
  // Use TableInfo.newBuilder() to construct.
  private TableInfo(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private TableInfo() {
    tableType_ = 0;
    tableName_ = "";
    userIdentity_ = "";
    totalRowCount_ = 0L;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private TableInfo(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
          case 8: {
            int rawValue = input.readEnum();

            tableType_ = rawValue;
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            tableName_ = s;
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();

            userIdentity_ = s;
            break;
          }
          case 32: {

            totalRowCount_ = input.readInt64();
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.innowireless.xdb5gcp.rui.RuiProto.internal_static_xdb_5gcp_rui_TableInfo_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.innowireless.xdb5gcp.rui.RuiProto.internal_static_xdb_5gcp_rui_TableInfo_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.innowireless.xdb5gcp.rui.TableInfo.class, com.innowireless.xdb5gcp.rui.TableInfo.Builder.class);
  }

  /**
   * Protobuf enum {@code xdb_5gcp.rui.TableInfo.TableType}
   */
  public enum TableType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>UNKNOWN = 0;</code>
     */
    UNKNOWN(0),
    /**
     * <code>ISA_HUB_TABLE = 1;</code>
     */
    ISA_HUB_TABLE(1),
    /**
     * <code>USER_TABLE = 2;</code>
     */
    USER_TABLE(2),
    /**
     * <code>MEMORY_TABLE = 3;</code>
     */
    MEMORY_TABLE(3),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>UNKNOWN = 0;</code>
     */
    public static final int UNKNOWN_VALUE = 0;
    /**
     * <code>ISA_HUB_TABLE = 1;</code>
     */
    public static final int ISA_HUB_TABLE_VALUE = 1;
    /**
     * <code>USER_TABLE = 2;</code>
     */
    public static final int USER_TABLE_VALUE = 2;
    /**
     * <code>MEMORY_TABLE = 3;</code>
     */
    public static final int MEMORY_TABLE_VALUE = 3;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static TableType valueOf(int value) {
      return forNumber(value);
    }

    public static TableType forNumber(int value) {
      switch (value) {
        case 0: return UNKNOWN;
        case 1: return ISA_HUB_TABLE;
        case 2: return USER_TABLE;
        case 3: return MEMORY_TABLE;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<TableType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        TableType> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<TableType>() {
            public TableType findValueByNumber(int number) {
              return TableType.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.innowireless.xdb5gcp.rui.TableInfo.getDescriptor().getEnumTypes().get(0);
    }

    private static final TableType[] VALUES = values();

    public static TableType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private TableType(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:xdb_5gcp.rui.TableInfo.TableType)
  }

  public static final int TABLE_TYPE_FIELD_NUMBER = 1;
  private int tableType_;
  /**
   * <code>.xdb_5gcp.rui.TableInfo.TableType table_type = 1;</code>
   */
  public int getTableTypeValue() {
    return tableType_;
  }
  /**
   * <code>.xdb_5gcp.rui.TableInfo.TableType table_type = 1;</code>
   */
  public com.innowireless.xdb5gcp.rui.TableInfo.TableType getTableType() {
    com.innowireless.xdb5gcp.rui.TableInfo.TableType result = com.innowireless.xdb5gcp.rui.TableInfo.TableType.valueOf(tableType_);
    return result == null ? com.innowireless.xdb5gcp.rui.TableInfo.TableType.UNRECOGNIZED : result;
  }

  public static final int TABLE_NAME_FIELD_NUMBER = 2;
  private volatile java.lang.Object tableName_;
  /**
   * <code>string table_name = 2;</code>
   */
  public java.lang.String getTableName() {
    java.lang.Object ref = tableName_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      tableName_ = s;
      return s;
    }
  }
  /**
   * <code>string table_name = 2;</code>
   */
  public com.google.protobuf.ByteString
      getTableNameBytes() {
    java.lang.Object ref = tableName_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      tableName_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int USER_IDENTITY_FIELD_NUMBER = 3;
  private volatile java.lang.Object userIdentity_;
  /**
   * <pre>
   * for USER_TABLE and MEMORY_TABLE
   * </pre>
   *
   * <code>string user_identity = 3;</code>
   */
  public java.lang.String getUserIdentity() {
    java.lang.Object ref = userIdentity_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      userIdentity_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * for USER_TABLE and MEMORY_TABLE
   * </pre>
   *
   * <code>string user_identity = 3;</code>
   */
  public com.google.protobuf.ByteString
      getUserIdentityBytes() {
    java.lang.Object ref = userIdentity_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      userIdentity_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int TOTAL_ROW_COUNT_FIELD_NUMBER = 4;
  private long totalRowCount_;
  /**
   * <pre>
   * for USER_TABLE and MEMORY_TABLE
   * </pre>
   *
   * <code>int64 total_row_count = 4;</code>
   */
  public long getTotalRowCount() {
    return totalRowCount_;
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (tableType_ != com.innowireless.xdb5gcp.rui.TableInfo.TableType.UNKNOWN.getNumber()) {
      output.writeEnum(1, tableType_);
    }
    if (!getTableNameBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, tableName_);
    }
    if (!getUserIdentityBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, userIdentity_);
    }
    if (totalRowCount_ != 0L) {
      output.writeInt64(4, totalRowCount_);
    }
    unknownFields.writeTo(output);
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (tableType_ != com.innowireless.xdb5gcp.rui.TableInfo.TableType.UNKNOWN.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(1, tableType_);
    }
    if (!getTableNameBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, tableName_);
    }
    if (!getUserIdentityBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, userIdentity_);
    }
    if (totalRowCount_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(4, totalRowCount_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.innowireless.xdb5gcp.rui.TableInfo)) {
      return super.equals(obj);
    }
    com.innowireless.xdb5gcp.rui.TableInfo other = (com.innowireless.xdb5gcp.rui.TableInfo) obj;

    boolean result = true;
    result = result && tableType_ == other.tableType_;
    result = result && getTableName()
        .equals(other.getTableName());
    result = result && getUserIdentity()
        .equals(other.getUserIdentity());
    result = result && (getTotalRowCount()
        == other.getTotalRowCount());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + TABLE_TYPE_FIELD_NUMBER;
    hash = (53 * hash) + tableType_;
    hash = (37 * hash) + TABLE_NAME_FIELD_NUMBER;
    hash = (53 * hash) + getTableName().hashCode();
    hash = (37 * hash) + USER_IDENTITY_FIELD_NUMBER;
    hash = (53 * hash) + getUserIdentity().hashCode();
    hash = (37 * hash) + TOTAL_ROW_COUNT_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getTotalRowCount());
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.innowireless.xdb5gcp.rui.TableInfo parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.innowireless.xdb5gcp.rui.TableInfo parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.innowireless.xdb5gcp.rui.TableInfo parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.innowireless.xdb5gcp.rui.TableInfo parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.innowireless.xdb5gcp.rui.TableInfo parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.innowireless.xdb5gcp.rui.TableInfo parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.innowireless.xdb5gcp.rui.TableInfo parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.innowireless.xdb5gcp.rui.TableInfo parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.innowireless.xdb5gcp.rui.TableInfo parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.innowireless.xdb5gcp.rui.TableInfo parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.innowireless.xdb5gcp.rui.TableInfo parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.innowireless.xdb5gcp.rui.TableInfo parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.innowireless.xdb5gcp.rui.TableInfo prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code xdb_5gcp.rui.TableInfo}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:xdb_5gcp.rui.TableInfo)
      com.innowireless.xdb5gcp.rui.TableInfoOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.innowireless.xdb5gcp.rui.RuiProto.internal_static_xdb_5gcp_rui_TableInfo_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.innowireless.xdb5gcp.rui.RuiProto.internal_static_xdb_5gcp_rui_TableInfo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.innowireless.xdb5gcp.rui.TableInfo.class, com.innowireless.xdb5gcp.rui.TableInfo.Builder.class);
    }

    // Construct using com.innowireless.xdb5gcp.rui.TableInfo.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      tableType_ = 0;

      tableName_ = "";

      userIdentity_ = "";

      totalRowCount_ = 0L;

      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.innowireless.xdb5gcp.rui.RuiProto.internal_static_xdb_5gcp_rui_TableInfo_descriptor;
    }

    public com.innowireless.xdb5gcp.rui.TableInfo getDefaultInstanceForType() {
      return com.innowireless.xdb5gcp.rui.TableInfo.getDefaultInstance();
    }

    public com.innowireless.xdb5gcp.rui.TableInfo build() {
      com.innowireless.xdb5gcp.rui.TableInfo result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public com.innowireless.xdb5gcp.rui.TableInfo buildPartial() {
      com.innowireless.xdb5gcp.rui.TableInfo result = new com.innowireless.xdb5gcp.rui.TableInfo(this);
      result.tableType_ = tableType_;
      result.tableName_ = tableName_;
      result.userIdentity_ = userIdentity_;
      result.totalRowCount_ = totalRowCount_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.innowireless.xdb5gcp.rui.TableInfo) {
        return mergeFrom((com.innowireless.xdb5gcp.rui.TableInfo)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.innowireless.xdb5gcp.rui.TableInfo other) {
      if (other == com.innowireless.xdb5gcp.rui.TableInfo.getDefaultInstance()) return this;
      if (other.tableType_ != 0) {
        setTableTypeValue(other.getTableTypeValue());
      }
      if (!other.getTableName().isEmpty()) {
        tableName_ = other.tableName_;
        onChanged();
      }
      if (!other.getUserIdentity().isEmpty()) {
        userIdentity_ = other.userIdentity_;
        onChanged();
      }
      if (other.getTotalRowCount() != 0L) {
        setTotalRowCount(other.getTotalRowCount());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.innowireless.xdb5gcp.rui.TableInfo parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.innowireless.xdb5gcp.rui.TableInfo) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private int tableType_ = 0;
    /**
     * <code>.xdb_5gcp.rui.TableInfo.TableType table_type = 1;</code>
     */
    public int getTableTypeValue() {
      return tableType_;
    }
    /**
     * <code>.xdb_5gcp.rui.TableInfo.TableType table_type = 1;</code>
     */
    public Builder setTableTypeValue(int value) {
      tableType_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>.xdb_5gcp.rui.TableInfo.TableType table_type = 1;</code>
     */
    public com.innowireless.xdb5gcp.rui.TableInfo.TableType getTableType() {
      com.innowireless.xdb5gcp.rui.TableInfo.TableType result = com.innowireless.xdb5gcp.rui.TableInfo.TableType.valueOf(tableType_);
      return result == null ? com.innowireless.xdb5gcp.rui.TableInfo.TableType.UNRECOGNIZED : result;
    }
    /**
     * <code>.xdb_5gcp.rui.TableInfo.TableType table_type = 1;</code>
     */
    public Builder setTableType(com.innowireless.xdb5gcp.rui.TableInfo.TableType value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      tableType_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.xdb_5gcp.rui.TableInfo.TableType table_type = 1;</code>
     */
    public Builder clearTableType() {
      
      tableType_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object tableName_ = "";
    /**
     * <code>string table_name = 2;</code>
     */
    public java.lang.String getTableName() {
      java.lang.Object ref = tableName_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        tableName_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string table_name = 2;</code>
     */
    public com.google.protobuf.ByteString
        getTableNameBytes() {
      java.lang.Object ref = tableName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        tableName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string table_name = 2;</code>
     */
    public Builder setTableName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      tableName_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string table_name = 2;</code>
     */
    public Builder clearTableName() {
      
      tableName_ = getDefaultInstance().getTableName();
      onChanged();
      return this;
    }
    /**
     * <code>string table_name = 2;</code>
     */
    public Builder setTableNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      tableName_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object userIdentity_ = "";
    /**
     * <pre>
     * for USER_TABLE and MEMORY_TABLE
     * </pre>
     *
     * <code>string user_identity = 3;</code>
     */
    public java.lang.String getUserIdentity() {
      java.lang.Object ref = userIdentity_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        userIdentity_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * for USER_TABLE and MEMORY_TABLE
     * </pre>
     *
     * <code>string user_identity = 3;</code>
     */
    public com.google.protobuf.ByteString
        getUserIdentityBytes() {
      java.lang.Object ref = userIdentity_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        userIdentity_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * for USER_TABLE and MEMORY_TABLE
     * </pre>
     *
     * <code>string user_identity = 3;</code>
     */
    public Builder setUserIdentity(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      userIdentity_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * for USER_TABLE and MEMORY_TABLE
     * </pre>
     *
     * <code>string user_identity = 3;</code>
     */
    public Builder clearUserIdentity() {
      
      userIdentity_ = getDefaultInstance().getUserIdentity();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * for USER_TABLE and MEMORY_TABLE
     * </pre>
     *
     * <code>string user_identity = 3;</code>
     */
    public Builder setUserIdentityBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      userIdentity_ = value;
      onChanged();
      return this;
    }

    private long totalRowCount_ ;
    /**
     * <pre>
     * for USER_TABLE and MEMORY_TABLE
     * </pre>
     *
     * <code>int64 total_row_count = 4;</code>
     */
    public long getTotalRowCount() {
      return totalRowCount_;
    }
    /**
     * <pre>
     * for USER_TABLE and MEMORY_TABLE
     * </pre>
     *
     * <code>int64 total_row_count = 4;</code>
     */
    public Builder setTotalRowCount(long value) {
      
      totalRowCount_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * for USER_TABLE and MEMORY_TABLE
     * </pre>
     *
     * <code>int64 total_row_count = 4;</code>
     */
    public Builder clearTotalRowCount() {
      
      totalRowCount_ = 0L;
      onChanged();
      return this;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:xdb_5gcp.rui.TableInfo)
  }

  // @@protoc_insertion_point(class_scope:xdb_5gcp.rui.TableInfo)
  private static final com.innowireless.xdb5gcp.rui.TableInfo DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.innowireless.xdb5gcp.rui.TableInfo();
  }

  public static com.innowireless.xdb5gcp.rui.TableInfo getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<TableInfo>
      PARSER = new com.google.protobuf.AbstractParser<TableInfo>() {
    public TableInfo parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new TableInfo(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<TableInfo> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<TableInfo> getParserForType() {
    return PARSER;
  }

  public com.innowireless.xdb5gcp.rui.TableInfo getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

