// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: xdb_5gcp_rui.proto

package com.innowireless.xdb5gcp.rui;

public interface TableInfoListRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:xdb_5gcp.rui.TableInfoListRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.xdb_5gcp.rui.TableInfoListRequest.RequestTableType table_type = 1;</code>
   */
  int getTableTypeValue();
  /**
   * <code>.xdb_5gcp.rui.TableInfoListRequest.RequestTableType table_type = 1;</code>
   */
  com.innowireless.xdb5gcp.rui.TableInfoListRequest.RequestTableType getTableType();

  /**
   * <pre>
   * if regex string is empty, xdb will return all existing tables  
   * </pre>
   *
   * <code>string table_name_regex = 2;</code>
   */
  java.lang.String getTableNameRegex();
  /**
   * <pre>
   * if regex string is empty, xdb will return all existing tables  
   * </pre>
   *
   * <code>string table_name_regex = 2;</code>
   */
  com.google.protobuf.ByteString
      getTableNameRegexBytes();
}
