// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: xdb_5gcp_rui.proto

package com.innowireless.xdb5gcp.rui;

/**
 * Protobuf type {@code xdb_5gcp.rui.TableInfoListRequest}
 */
public  final class TableInfoListRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:xdb_5gcp.rui.TableInfoListRequest)
    TableInfoListRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use TableInfoListRequest.newBuilder() to construct.
  private TableInfoListRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private TableInfoListRequest() {
    tableType_ = 0;
    tableNameRegex_ = "";
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private TableInfoListRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
          case 8: {
            int rawValue = input.readEnum();

            tableType_ = rawValue;
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            tableNameRegex_ = s;
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.innowireless.xdb5gcp.rui.RuiProto.internal_static_xdb_5gcp_rui_TableInfoListRequest_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.innowireless.xdb5gcp.rui.RuiProto.internal_static_xdb_5gcp_rui_TableInfoListRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.innowireless.xdb5gcp.rui.TableInfoListRequest.class, com.innowireless.xdb5gcp.rui.TableInfoListRequest.Builder.class);
  }

  /**
   * Protobuf enum {@code xdb_5gcp.rui.TableInfoListRequest.RequestTableType}
   */
  public enum RequestTableType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>ALL_TABLE = 0;</code>
     */
    ALL_TABLE(0),
    /**
     * <code>ISA_HUB_TABLE = 1;</code>
     */
    ISA_HUB_TABLE(1),
    /**
     * <code>USER_TABLE = 2;</code>
     */
    USER_TABLE(2),
    /**
     * <code>MEMORY_TABLE = 3;</code>
     */
    MEMORY_TABLE(3),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>ALL_TABLE = 0;</code>
     */
    public static final int ALL_TABLE_VALUE = 0;
    /**
     * <code>ISA_HUB_TABLE = 1;</code>
     */
    public static final int ISA_HUB_TABLE_VALUE = 1;
    /**
     * <code>USER_TABLE = 2;</code>
     */
    public static final int USER_TABLE_VALUE = 2;
    /**
     * <code>MEMORY_TABLE = 3;</code>
     */
    public static final int MEMORY_TABLE_VALUE = 3;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static RequestTableType valueOf(int value) {
      return forNumber(value);
    }

    public static RequestTableType forNumber(int value) {
      switch (value) {
        case 0: return ALL_TABLE;
        case 1: return ISA_HUB_TABLE;
        case 2: return USER_TABLE;
        case 3: return MEMORY_TABLE;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<RequestTableType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        RequestTableType> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<RequestTableType>() {
            public RequestTableType findValueByNumber(int number) {
              return RequestTableType.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.innowireless.xdb5gcp.rui.TableInfoListRequest.getDescriptor().getEnumTypes().get(0);
    }

    private static final RequestTableType[] VALUES = values();

    public static RequestTableType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private RequestTableType(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:xdb_5gcp.rui.TableInfoListRequest.RequestTableType)
  }

  public static final int TABLE_TYPE_FIELD_NUMBER = 1;
  private int tableType_;
  /**
   * <code>.xdb_5gcp.rui.TableInfoListRequest.RequestTableType table_type = 1;</code>
   */
  public int getTableTypeValue() {
    return tableType_;
  }
  /**
   * <code>.xdb_5gcp.rui.TableInfoListRequest.RequestTableType table_type = 1;</code>
   */
  public com.innowireless.xdb5gcp.rui.TableInfoListRequest.RequestTableType getTableType() {
    com.innowireless.xdb5gcp.rui.TableInfoListRequest.RequestTableType result = com.innowireless.xdb5gcp.rui.TableInfoListRequest.RequestTableType.valueOf(tableType_);
    return result == null ? com.innowireless.xdb5gcp.rui.TableInfoListRequest.RequestTableType.UNRECOGNIZED : result;
  }

  public static final int TABLE_NAME_REGEX_FIELD_NUMBER = 2;
  private volatile java.lang.Object tableNameRegex_;
  /**
   * <pre>
   * if regex string is empty, xdb will return all existing tables  
   * </pre>
   *
   * <code>string table_name_regex = 2;</code>
   */
  public java.lang.String getTableNameRegex() {
    java.lang.Object ref = tableNameRegex_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      tableNameRegex_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * if regex string is empty, xdb will return all existing tables  
   * </pre>
   *
   * <code>string table_name_regex = 2;</code>
   */
  public com.google.protobuf.ByteString
      getTableNameRegexBytes() {
    java.lang.Object ref = tableNameRegex_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      tableNameRegex_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (tableType_ != com.innowireless.xdb5gcp.rui.TableInfoListRequest.RequestTableType.ALL_TABLE.getNumber()) {
      output.writeEnum(1, tableType_);
    }
    if (!getTableNameRegexBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, tableNameRegex_);
    }
    unknownFields.writeTo(output);
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (tableType_ != com.innowireless.xdb5gcp.rui.TableInfoListRequest.RequestTableType.ALL_TABLE.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(1, tableType_);
    }
    if (!getTableNameRegexBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, tableNameRegex_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.innowireless.xdb5gcp.rui.TableInfoListRequest)) {
      return super.equals(obj);
    }
    com.innowireless.xdb5gcp.rui.TableInfoListRequest other = (com.innowireless.xdb5gcp.rui.TableInfoListRequest) obj;

    boolean result = true;
    result = result && tableType_ == other.tableType_;
    result = result && getTableNameRegex()
        .equals(other.getTableNameRegex());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + TABLE_TYPE_FIELD_NUMBER;
    hash = (53 * hash) + tableType_;
    hash = (37 * hash) + TABLE_NAME_REGEX_FIELD_NUMBER;
    hash = (53 * hash) + getTableNameRegex().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.innowireless.xdb5gcp.rui.TableInfoListRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.innowireless.xdb5gcp.rui.TableInfoListRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.innowireless.xdb5gcp.rui.TableInfoListRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.innowireless.xdb5gcp.rui.TableInfoListRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.innowireless.xdb5gcp.rui.TableInfoListRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.innowireless.xdb5gcp.rui.TableInfoListRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.innowireless.xdb5gcp.rui.TableInfoListRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.innowireless.xdb5gcp.rui.TableInfoListRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.innowireless.xdb5gcp.rui.TableInfoListRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.innowireless.xdb5gcp.rui.TableInfoListRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.innowireless.xdb5gcp.rui.TableInfoListRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.innowireless.xdb5gcp.rui.TableInfoListRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.innowireless.xdb5gcp.rui.TableInfoListRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code xdb_5gcp.rui.TableInfoListRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:xdb_5gcp.rui.TableInfoListRequest)
      com.innowireless.xdb5gcp.rui.TableInfoListRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.innowireless.xdb5gcp.rui.RuiProto.internal_static_xdb_5gcp_rui_TableInfoListRequest_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.innowireless.xdb5gcp.rui.RuiProto.internal_static_xdb_5gcp_rui_TableInfoListRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.innowireless.xdb5gcp.rui.TableInfoListRequest.class, com.innowireless.xdb5gcp.rui.TableInfoListRequest.Builder.class);
    }

    // Construct using com.innowireless.xdb5gcp.rui.TableInfoListRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      tableType_ = 0;

      tableNameRegex_ = "";

      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.innowireless.xdb5gcp.rui.RuiProto.internal_static_xdb_5gcp_rui_TableInfoListRequest_descriptor;
    }

    public com.innowireless.xdb5gcp.rui.TableInfoListRequest getDefaultInstanceForType() {
      return com.innowireless.xdb5gcp.rui.TableInfoListRequest.getDefaultInstance();
    }

    public com.innowireless.xdb5gcp.rui.TableInfoListRequest build() {
      com.innowireless.xdb5gcp.rui.TableInfoListRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public com.innowireless.xdb5gcp.rui.TableInfoListRequest buildPartial() {
      com.innowireless.xdb5gcp.rui.TableInfoListRequest result = new com.innowireless.xdb5gcp.rui.TableInfoListRequest(this);
      result.tableType_ = tableType_;
      result.tableNameRegex_ = tableNameRegex_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.innowireless.xdb5gcp.rui.TableInfoListRequest) {
        return mergeFrom((com.innowireless.xdb5gcp.rui.TableInfoListRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.innowireless.xdb5gcp.rui.TableInfoListRequest other) {
      if (other == com.innowireless.xdb5gcp.rui.TableInfoListRequest.getDefaultInstance()) return this;
      if (other.tableType_ != 0) {
        setTableTypeValue(other.getTableTypeValue());
      }
      if (!other.getTableNameRegex().isEmpty()) {
        tableNameRegex_ = other.tableNameRegex_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.innowireless.xdb5gcp.rui.TableInfoListRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.innowireless.xdb5gcp.rui.TableInfoListRequest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private int tableType_ = 0;
    /**
     * <code>.xdb_5gcp.rui.TableInfoListRequest.RequestTableType table_type = 1;</code>
     */
    public int getTableTypeValue() {
      return tableType_;
    }
    /**
     * <code>.xdb_5gcp.rui.TableInfoListRequest.RequestTableType table_type = 1;</code>
     */
    public Builder setTableTypeValue(int value) {
      tableType_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>.xdb_5gcp.rui.TableInfoListRequest.RequestTableType table_type = 1;</code>
     */
    public com.innowireless.xdb5gcp.rui.TableInfoListRequest.RequestTableType getTableType() {
      com.innowireless.xdb5gcp.rui.TableInfoListRequest.RequestTableType result = com.innowireless.xdb5gcp.rui.TableInfoListRequest.RequestTableType.valueOf(tableType_);
      return result == null ? com.innowireless.xdb5gcp.rui.TableInfoListRequest.RequestTableType.UNRECOGNIZED : result;
    }
    /**
     * <code>.xdb_5gcp.rui.TableInfoListRequest.RequestTableType table_type = 1;</code>
     */
    public Builder setTableType(com.innowireless.xdb5gcp.rui.TableInfoListRequest.RequestTableType value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      tableType_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.xdb_5gcp.rui.TableInfoListRequest.RequestTableType table_type = 1;</code>
     */
    public Builder clearTableType() {
      
      tableType_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object tableNameRegex_ = "";
    /**
     * <pre>
     * if regex string is empty, xdb will return all existing tables  
     * </pre>
     *
     * <code>string table_name_regex = 2;</code>
     */
    public java.lang.String getTableNameRegex() {
      java.lang.Object ref = tableNameRegex_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        tableNameRegex_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * if regex string is empty, xdb will return all existing tables  
     * </pre>
     *
     * <code>string table_name_regex = 2;</code>
     */
    public com.google.protobuf.ByteString
        getTableNameRegexBytes() {
      java.lang.Object ref = tableNameRegex_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        tableNameRegex_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * if regex string is empty, xdb will return all existing tables  
     * </pre>
     *
     * <code>string table_name_regex = 2;</code>
     */
    public Builder setTableNameRegex(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      tableNameRegex_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * if regex string is empty, xdb will return all existing tables  
     * </pre>
     *
     * <code>string table_name_regex = 2;</code>
     */
    public Builder clearTableNameRegex() {
      
      tableNameRegex_ = getDefaultInstance().getTableNameRegex();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * if regex string is empty, xdb will return all existing tables  
     * </pre>
     *
     * <code>string table_name_regex = 2;</code>
     */
    public Builder setTableNameRegexBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      tableNameRegex_ = value;
      onChanged();
      return this;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:xdb_5gcp.rui.TableInfoListRequest)
  }

  // @@protoc_insertion_point(class_scope:xdb_5gcp.rui.TableInfoListRequest)
  private static final com.innowireless.xdb5gcp.rui.TableInfoListRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.innowireless.xdb5gcp.rui.TableInfoListRequest();
  }

  public static com.innowireless.xdb5gcp.rui.TableInfoListRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<TableInfoListRequest>
      PARSER = new com.google.protobuf.AbstractParser<TableInfoListRequest>() {
    public TableInfoListRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new TableInfoListRequest(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<TableInfoListRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<TableInfoListRequest> getParserForType() {
    return PARSER;
  }

  public com.innowireless.xdb5gcp.rui.TableInfoListRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

