// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: xdb_5gcp_rui.proto

package com.innowireless.xdb5gcp.rui;

public interface TableSchemaResultOrBuilder extends
    // @@protoc_insertion_point(interface_extends:xdb_5gcp.rui.TableSchemaResult)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.xdb_5gcp.rui.BaseResult base_result = 1;</code>
   */
  boolean hasBaseResult();
  /**
   * <code>.xdb_5gcp.rui.BaseResult base_result = 1;</code>
   */
  com.innowireless.xdb5gcp.rui.BaseResult getBaseResult();
  /**
   * <code>.xdb_5gcp.rui.BaseResult base_result = 1;</code>
   */
  com.innowireless.xdb5gcp.rui.BaseResultOrBuilder getBaseResultOrBuilder();

  /**
   * <code>.xdb_5gcp.rui.TableInfo table_info = 2;</code>
   */
  boolean hasTableInfo();
  /**
   * <code>.xdb_5gcp.rui.TableInfo table_info = 2;</code>
   */
  com.innowireless.xdb5gcp.rui.TableInfo getTableInfo();
  /**
   * <code>.xdb_5gcp.rui.TableInfo table_info = 2;</code>
   */
  com.innowireless.xdb5gcp.rui.TableInfoOrBuilder getTableInfoOrBuilder();

  /**
   * <code>repeated .xdb_5gcp.rui.TableSchemaResult.ColumnInfo column_info_list = 3;</code>
   */
  java.util.List<com.innowireless.xdb5gcp.rui.TableSchemaResult.ColumnInfo> 
      getColumnInfoListList();
  /**
   * <code>repeated .xdb_5gcp.rui.TableSchemaResult.ColumnInfo column_info_list = 3;</code>
   */
  com.innowireless.xdb5gcp.rui.TableSchemaResult.ColumnInfo getColumnInfoList(int index);
  /**
   * <code>repeated .xdb_5gcp.rui.TableSchemaResult.ColumnInfo column_info_list = 3;</code>
   */
  int getColumnInfoListCount();
  /**
   * <code>repeated .xdb_5gcp.rui.TableSchemaResult.ColumnInfo column_info_list = 3;</code>
   */
  java.util.List<? extends com.innowireless.xdb5gcp.rui.TableSchemaResult.ColumnInfoOrBuilder> 
      getColumnInfoListOrBuilderList();
  /**
   * <code>repeated .xdb_5gcp.rui.TableSchemaResult.ColumnInfo column_info_list = 3;</code>
   */
  com.innowireless.xdb5gcp.rui.TableSchemaResult.ColumnInfoOrBuilder getColumnInfoListOrBuilder(
      int index);

  /**
   * <code>repeated .xdb_5gcp.rui.TableSchemaResult.TimePartition time_partition_list = 4;</code>
   */
  java.util.List<com.innowireless.xdb5gcp.rui.TableSchemaResult.TimePartition> 
      getTimePartitionListList();
  /**
   * <code>repeated .xdb_5gcp.rui.TableSchemaResult.TimePartition time_partition_list = 4;</code>
   */
  com.innowireless.xdb5gcp.rui.TableSchemaResult.TimePartition getTimePartitionList(int index);
  /**
   * <code>repeated .xdb_5gcp.rui.TableSchemaResult.TimePartition time_partition_list = 4;</code>
   */
  int getTimePartitionListCount();
  /**
   * <code>repeated .xdb_5gcp.rui.TableSchemaResult.TimePartition time_partition_list = 4;</code>
   */
  java.util.List<? extends com.innowireless.xdb5gcp.rui.TableSchemaResult.TimePartitionOrBuilder> 
      getTimePartitionListOrBuilderList();
  /**
   * <code>repeated .xdb_5gcp.rui.TableSchemaResult.TimePartition time_partition_list = 4;</code>
   */
  com.innowireless.xdb5gcp.rui.TableSchemaResult.TimePartitionOrBuilder getTimePartitionListOrBuilder(
      int index);
}
