// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: xdb_5gcp_rui.proto

package com.innowireless.xdb5gcp.rui;

public interface TableNameOrBuilder extends
    // @@protoc_insertion_point(interface_extends:xdb_5gcp.rui.TableName)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string table_name = 1;</code>
   */
  java.lang.String getTableName();
  /**
   * <code>string table_name = 1;</code>
   */
  com.google.protobuf.ByteString
      getTableNameBytes();
}
