// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: xdb_5gcp_rui.proto

package com.innowireless.xdb5gcp.rui;

public interface TableInfoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:xdb_5gcp.rui.TableInfo)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.xdb_5gcp.rui.TableInfo.TableType table_type = 1;</code>
   */
  int getTableTypeValue();
  /**
   * <code>.xdb_5gcp.rui.TableInfo.TableType table_type = 1;</code>
   */
  com.innowireless.xdb5gcp.rui.TableInfo.TableType getTableType();

  /**
   * <code>string table_name = 2;</code>
   */
  java.lang.String getTableName();
  /**
   * <code>string table_name = 2;</code>
   */
  com.google.protobuf.ByteString
      getTableNameBytes();

  /**
   * <pre>
   * for USER_TABLE and MEMORY_TABLE
   * </pre>
   *
   * <code>string user_identity = 3;</code>
   */
  java.lang.String getUserIdentity();
  /**
   * <pre>
   * for USER_TABLE and MEMORY_TABLE
   * </pre>
   *
   * <code>string user_identity = 3;</code>
   */
  com.google.protobuf.ByteString
      getUserIdentityBytes();

  /**
   * <pre>
   * for USER_TABLE and MEMORY_TABLE
   * </pre>
   *
   * <code>int64 total_row_count = 4;</code>
   */
  long getTotalRowCount();
}
